package org.sugarj.driver.transformations.renaming;

import org.strategoxt.stratego_lib.*;
import org.strategoxt.lang.*;
import org.spoofax.interpreter.terms.*;
import static org.strategoxt.lang.Term.*;
import org.spoofax.interpreter.library.AbstractPrimitive;
import java.util.ArrayList;
import java.lang.ref.WeakReference;

@SuppressWarnings("unused") public class InteropRegisterer extends org.strategoxt.lang.InteropRegisterer 
{ 
  @Override public void register(org.spoofax.interpreter.core.IContext context, Context compiledContext)
  { 
    register(context, compiledContext, context.getVarScope());
  }

  @Override public void registerLazy(org.spoofax.interpreter.core.IContext context, Context compiledContext, ClassLoader classLoader)
  { 
    registerLazy(context, compiledContext, classLoader, context.getVarScope());
  }

  private void register(org.spoofax.interpreter.core.IContext context, Context compiledContext, org.spoofax.interpreter.core.VarScope varScope)
  { 
    compiledContext.registerComponent("renaming");
    renaming.init(compiledContext);
    varScope.addSVar("rename_java_0_3", new InteropSDefT(rename_java_0_3.instance, context));
    varScope.addSVar("do_rename_java_0_3", new InteropSDefT(do_rename_java_0_3.instance, context));
    varScope.addSVar("match_pkgs_java_0_0", new InteropSDefT(match_pkgs_java_0_0.instance, context));
    varScope.addSVar("CompilationUnit_3_0", new InteropSDefT($Compilation$Unit_3_0.instance, context));
    varScope.addSVar("Semicolon_0_0", new InteropSDefT($Semicolon_0_0.instance, context));
    varScope.addSVar("StaticImportOnDemandDec_1_0", new InteropSDefT($Static$Import$On$Demand$Dec_1_0.instance, context));
    varScope.addSVar("StaticImportDec_2_0", new InteropSDefT($Static$Import$Dec_2_0.instance, context));
    varScope.addSVar("TypeImportOnDemandDec_1_0", new InteropSDefT($Type$Import$On$Demand$Dec_1_0.instance, context));
    varScope.addSVar("TypeImportDec_1_0", new InteropSDefT($Type$Import$Dec_1_0.instance, context));
    varScope.addSVar("PackageDec_2_0", new InteropSDefT($Package$Dec_2_0.instance, context));
    varScope.addSVar("ElemValArrayInit_1_0", new InteropSDefT($Elem$Val$Array$Init_1_0.instance, context));
    varScope.addSVar("ElemValPair_2_0", new InteropSDefT($Elem$Val$Pair_2_0.instance, context));
    varScope.addSVar("MarkerAnno_1_0", new InteropSDefT($Marker$Anno_1_0.instance, context));
    varScope.addSVar("SingleElemAnno_2_0", new InteropSDefT($Single$Elem$Anno_2_0.instance, context));
    varScope.addSVar("GenericMethod_3_0", new InteropSDefT($Generic$Method_3_0.instance, context));
    varScope.addSVar("QSuperMethod_3_0", new InteropSDefT($Q$Super$Method_3_0.instance, context));
    varScope.addSVar("SuperMethod_2_0", new InteropSDefT($Super$Method_2_0.instance, context));
    varScope.addSVar("Method_3_0", new InteropSDefT($Method_3_0.instance, context));
    varScope.addSVar("Method_1_0", new InteropSDefT($Method_1_0.instance, context));
    varScope.addSVar("QSuperField_2_0", new InteropSDefT($Q$Super$Field_2_0.instance, context));
    varScope.addSVar("SuperField_1_0", new InteropSDefT($Super$Field_1_0.instance, context));
    varScope.addSVar("Field_2_0", new InteropSDefT($Field_2_0.instance, context));
    varScope.addSVar("Dim_1_0", new InteropSDefT($Dim_1_0.instance, context));
    varScope.addSVar("UnboundWld_1_0", new InteropSDefT($Unbound$Wld_1_0.instance, context));
    varScope.addSVar("NewArray_3_0", new InteropSDefT($New$Array_3_0.instance, context));
    varScope.addSVar("ImplementsDec_1_0", new InteropSDefT($Implements$Dec_1_0.instance, context));
    varScope.addSVar("SuperDec_1_0", new InteropSDefT($Super$Dec_1_0.instance, context));
    varScope.addSVar("ClassDecHead_5_0", new InteropSDefT($Class$Dec$Head_5_0.instance, context));
    varScope.addSVar("ClassBody_1_0", new InteropSDefT($Class$Body_1_0.instance, context));
    varScope.addSVar("ClassDec_2_0", new InteropSDefT($Class$Dec_2_0.instance, context));
    varScope.addSVar("ExtendsInterfaces_1_0", new InteropSDefT($Extends$Interfaces_1_0.instance, context));
    varScope.addSVar("InterfaceDecHead_4_0", new InteropSDefT($Interface$Dec$Head_4_0.instance, context));
    varScope.addSVar("InterfaceDec_2_0", new InteropSDefT($Interface$Dec_2_0.instance, context));
    varScope.addSVar("DefaultVal_1_0", new InteropSDefT($Default$Val_1_0.instance, context));
    varScope.addSVar("AnnoMethodDec_4_0", new InteropSDefT($Anno$Method$Dec_4_0.instance, context));
    varScope.addSVar("AnnoDecHead_2_0", new InteropSDefT($Anno$Dec$Head_2_0.instance, context));
    varScope.addSVar("AnnoDec_2_0", new InteropSDefT($Anno$Dec_2_0.instance, context));
    varScope.addSVar("DeprAbstractMethodDec_7_0", new InteropSDefT($Depr$Abstract$Method$Dec_7_0.instance, context));
    varScope.addSVar("AbstractMethodDec_6_0", new InteropSDefT($Abstract$Method$Dec_6_0.instance, context));
    varScope.addSVar("ConstantDec_3_0", new InteropSDefT($Constant$Dec_3_0.instance, context));
    varScope.addSVar("EnumBodyDecs_1_0", new InteropSDefT($Enum$Body$Decs_1_0.instance, context));
    varScope.addSVar("EnumConst_3_0", new InteropSDefT($Enum$Const_3_0.instance, context));
    varScope.addSVar("EnumBody_2_0", new InteropSDefT($Enum$Body_2_0.instance, context));
    varScope.addSVar("EnumDecHead_3_0", new InteropSDefT($Enum$Dec$Head_3_0.instance, context));
    varScope.addSVar("EnumDec_2_0", new InteropSDefT($Enum$Dec_2_0.instance, context));
    varScope.addSVar("QSuperConstrInv_3_0", new InteropSDefT($Q$Super$Constr$Inv_3_0.instance, context));
    varScope.addSVar("SuperConstrInv_2_0", new InteropSDefT($Super$Constr$Inv_2_0.instance, context));
    varScope.addSVar("AltConstrInv_2_0", new InteropSDefT($Alt$Constr$Inv_2_0.instance, context));
    varScope.addSVar("ConstrBody_2_0", new InteropSDefT($Constr$Body_2_0.instance, context));
    varScope.addSVar("ConstrDecHead_5_0", new InteropSDefT($Constr$Dec$Head_5_0.instance, context));
    varScope.addSVar("ConstrDec_2_0", new InteropSDefT($Constr$Dec_2_0.instance, context));
    varScope.addSVar("StaticInit_1_0", new InteropSDefT($Static$Init_1_0.instance, context));
    varScope.addSVar("InstanceInit_1_0", new InteropSDefT($Instance$Init_1_0.instance, context));
    varScope.addSVar("NoMethodBody_0_0", new InteropSDefT($No$Method$Body_0_0.instance, context));
    varScope.addSVar("ThrowsDec_1_0", new InteropSDefT($Throws$Dec_1_0.instance, context));
    varScope.addSVar("VarArityParam_3_0", new InteropSDefT($Var$Arity$Param_3_0.instance, context));
    varScope.addSVar("Param_3_0", new InteropSDefT($Param_3_0.instance, context));
    varScope.addSVar("Void_0_0", new InteropSDefT($Void_0_0.instance, context));
    varScope.addSVar("DeprMethodDecHead_7_0", new InteropSDefT($Depr$Method$Dec$Head_7_0.instance, context));
    varScope.addSVar("MethodDecHead_6_0", new InteropSDefT($Method$Dec$Head_6_0.instance, context));
    varScope.addSVar("MethodDec_2_0", new InteropSDefT($Method$Dec_2_0.instance, context));
    varScope.addSVar("ClassDecStm_1_0", new InteropSDefT($Class$Dec$Stm_1_0.instance, context));
    varScope.addSVar("Block_1_0", new InteropSDefT($Block_1_0.instance, context));
    varScope.addSVar("Default_0_0", new InteropSDefT($Default_0_0.instance, context));
    varScope.addSVar("Case_1_0", new InteropSDefT($Case_1_0.instance, context));
    varScope.addSVar("SwitchGroup_2_0", new InteropSDefT($Switch$Group_2_0.instance, context));
    varScope.addSVar("SwitchBlock_2_0", new InteropSDefT($Switch$Block_2_0.instance, context));
    varScope.addSVar("Try_3_0", new InteropSDefT($Try_3_0.instance, context));
    varScope.addSVar("Try_2_0", new InteropSDefT($Try_2_0.instance, context));
    varScope.addSVar("Synchronized_2_0", new InteropSDefT($Synchronized_2_0.instance, context));
    varScope.addSVar("Throw_1_0", new InteropSDefT($Throw_1_0.instance, context));
    varScope.addSVar("Return_1_0", new InteropSDefT($Return_1_0.instance, context));
    varScope.addSVar("Continue_1_0", new InteropSDefT($Continue_1_0.instance, context));
    varScope.addSVar("Break_1_0", new InteropSDefT($Break_1_0.instance, context));
    varScope.addSVar("ForEach_3_0", new InteropSDefT($For$Each_3_0.instance, context));
    varScope.addSVar("For_4_0", new InteropSDefT($For_4_0.instance, context));
    varScope.addSVar("DoWhile_2_0", new InteropSDefT($Do$While_2_0.instance, context));
    varScope.addSVar("While_2_0", new InteropSDefT($While_2_0.instance, context));
    varScope.addSVar("Switch_2_0", new InteropSDefT($Switch_2_0.instance, context));
    varScope.addSVar("AssertStm_2_0", new InteropSDefT($Assert$Stm_2_0.instance, context));
    varScope.addSVar("AssertStm_1_0", new InteropSDefT($Assert$Stm_1_0.instance, context));
    varScope.addSVar("If_3_0", new InteropSDefT($If_3_0.instance, context));
    varScope.addSVar("If_2_0", new InteropSDefT($If_2_0.instance, context));
    varScope.addSVar("ExprStm_1_0", new InteropSDefT($Expr$Stm_1_0.instance, context));
    varScope.addSVar("Labeled_2_0", new InteropSDefT($Labeled_2_0.instance, context));
    varScope.addSVar("Empty_0_0", new InteropSDefT($Empty_0_0.instance, context));
    varScope.addSVar("LocalVarDec_3_0", new InteropSDefT($Local$Var$Dec_3_0.instance, context));
    varScope.addSVar("LocalVarDecStm_1_0", new InteropSDefT($Local$Var$Dec$Stm_1_0.instance, context));
    varScope.addSVar("Dim_0_0", new InteropSDefT($Dim_0_0.instance, context));
    varScope.addSVar("ArrayVarDecId_2_0", new InteropSDefT($Array$Var$Dec$Id_2_0.instance, context));
    varScope.addSVar("VarDec_2_0", new InteropSDefT($Var$Dec_2_0.instance, context));
    varScope.addSVar("VarDec_1_0", new InteropSDefT($Var$Dec_1_0.instance, context));
    varScope.addSVar("FieldDec_3_0", new InteropSDefT($Field$Dec_3_0.instance, context));
    varScope.addSVar("ArrayInit_1_0", new InteropSDefT($Array$Init_1_0.instance, context));
    varScope.addSVar("VoidClass_0_0", new InteropSDefT($Void$Class_0_0.instance, context));
    varScope.addSVar("Class_1_0", new InteropSDefT($Class_1_0.instance, context));
    varScope.addSVar("AssignOr_2_0", new InteropSDefT($Assign$Or_2_0.instance, context));
    varScope.addSVar("AssignExcOr_2_0", new InteropSDefT($Assign$Exc$Or_2_0.instance, context));
    varScope.addSVar("AssignAnd_2_0", new InteropSDefT($Assign$And_2_0.instance, context));
    varScope.addSVar("AssignURightShift_2_0", new InteropSDefT($Assign$U$Right$Shift_2_0.instance, context));
    varScope.addSVar("AssignRightShift_2_0", new InteropSDefT($Assign$Right$Shift_2_0.instance, context));
    varScope.addSVar("AssignLeftShift_2_0", new InteropSDefT($Assign$Left$Shift_2_0.instance, context));
    varScope.addSVar("AssignMinus_2_0", new InteropSDefT($Assign$Minus_2_0.instance, context));
    varScope.addSVar("AssignPlus_2_0", new InteropSDefT($Assign$Plus_2_0.instance, context));
    varScope.addSVar("AssignRemain_2_0", new InteropSDefT($Assign$Remain_2_0.instance, context));
    varScope.addSVar("AssignDiv_2_0", new InteropSDefT($Assign$Div_2_0.instance, context));
    varScope.addSVar("AssignMul_2_0", new InteropSDefT($Assign$Mul_2_0.instance, context));
    varScope.addSVar("Assign_2_0", new InteropSDefT($Assign_2_0.instance, context));
    varScope.addSVar("Or_2_0", new InteropSDefT($Or_2_0.instance, context));
    varScope.addSVar("ExcOr_2_0", new InteropSDefT($Exc$Or_2_0.instance, context));
    varScope.addSVar("And_2_0", new InteropSDefT($And_2_0.instance, context));
    varScope.addSVar("LazyOr_2_0", new InteropSDefT($Lazy$Or_2_0.instance, context));
    varScope.addSVar("LazyAnd_2_0", new InteropSDefT($Lazy$And_2_0.instance, context));
    varScope.addSVar("NotEq_2_0", new InteropSDefT($Not$Eq_2_0.instance, context));
    varScope.addSVar("Eq_2_0", new InteropSDefT($Eq_2_0.instance, context));
    varScope.addSVar("GtEq_2_0", new InteropSDefT($Gt$Eq_2_0.instance, context));
    varScope.addSVar("LtEq_2_0", new InteropSDefT($Lt$Eq_2_0.instance, context));
    varScope.addSVar("Gt_2_0", new InteropSDefT($Gt_2_0.instance, context));
    varScope.addSVar("Lt_2_0", new InteropSDefT($Lt_2_0.instance, context));
    varScope.addSVar("URightShift_2_0", new InteropSDefT($U$Right$Shift_2_0.instance, context));
    varScope.addSVar("RightShift_2_0", new InteropSDefT($Right$Shift_2_0.instance, context));
    varScope.addSVar("LeftShift_2_0", new InteropSDefT($Left$Shift_2_0.instance, context));
    varScope.addSVar("Minus_2_0", new InteropSDefT($Minus_2_0.instance, context));
    varScope.addSVar("Plus_2_0", new InteropSDefT($Plus_2_0.instance, context));
    varScope.addSVar("Remain_2_0", new InteropSDefT($Remain_2_0.instance, context));
    varScope.addSVar("Div_2_0", new InteropSDefT($Div_2_0.instance, context));
    varScope.addSVar("Mul_2_0", new InteropSDefT($Mul_2_0.instance, context));
    varScope.addSVar("InstanceOf_2_0", new InteropSDefT($Instance$Of_2_0.instance, context));
    varScope.addSVar("CastRef_2_0", new InteropSDefT($Cast$Ref_2_0.instance, context));
    varScope.addSVar("CastPrim_2_0", new InteropSDefT($Cast$Prim_2_0.instance, context));
    varScope.addSVar("Not_1_0", new InteropSDefT($Not_1_0.instance, context));
    varScope.addSVar("Complement_1_0", new InteropSDefT($Complement_1_0.instance, context));
    varScope.addSVar("PreDecr_1_0", new InteropSDefT($Pre$Decr_1_0.instance, context));
    varScope.addSVar("PreIncr_1_0", new InteropSDefT($Pre$Incr_1_0.instance, context));
    varScope.addSVar("Minus_1_0", new InteropSDefT($Minus_1_0.instance, context));
    varScope.addSVar("Plus_1_0", new InteropSDefT($Plus_1_0.instance, context));
    varScope.addSVar("PostDecr_1_0", new InteropSDefT($Post$Decr_1_0.instance, context));
    varScope.addSVar("PostIncr_1_0", new InteropSDefT($Post$Incr_1_0.instance, context));
    varScope.addSVar("Invoke_2_0", new InteropSDefT($Invoke_2_0.instance, context));
    varScope.addSVar("QNewInstance_6_0", new InteropSDefT($Q$New$Instance_6_0.instance, context));
    varScope.addSVar("NewInstance_4_0", new InteropSDefT($New$Instance_4_0.instance, context));
    varScope.addSVar("QThis_1_0", new InteropSDefT($Q$This_1_0.instance, context));
    varScope.addSVar("This_0_0", new InteropSDefT($This_0_0.instance, context));
    varScope.addSVar("Lit_1_0", new InteropSDefT($Lit_1_0.instance, context));
    varScope.addSVar("ArrayType_1_0", new InteropSDefT($Array$Type_1_0.instance, context));
    varScope.addSVar("TypeVar_1_0", new InteropSDefT($Type$Var_1_0.instance, context));
    varScope.addSVar("Member_3_0", new InteropSDefT($Member_3_0.instance, context));
    varScope.addSVar("InterfaceType_2_0", new InteropSDefT($Interface$Type_2_0.instance, context));
    varScope.addSVar("ClassType_2_0", new InteropSDefT($Class$Type_2_0.instance, context));
    varScope.addSVar("ClassOrInterfaceType_2_0", new InteropSDefT($Class$Or$Interface$Type_2_0.instance, context));
    varScope.addSVar("TypeParams_1_0", new InteropSDefT($Type$Params_1_0.instance, context));
    varScope.addSVar("TypeBound_1_0", new InteropSDefT($Type$Bound_1_0.instance, context));
    varScope.addSVar("TypeParam_2_0", new InteropSDefT($Type$Param_2_0.instance, context));
    varScope.addSVar("WildcardLowerBound_1_0", new InteropSDefT($Wildcard$Lower$Bound_1_0.instance, context));
    varScope.addSVar("WildcardUpperBound_1_0", new InteropSDefT($Wildcard$Upper$Bound_1_0.instance, context));
    varScope.addSVar("Wildcard_1_0", new InteropSDefT($Wildcard_1_0.instance, context));
    varScope.addSVar("TypeArgs_1_0", new InteropSDefT($Type$Args_1_0.instance, context));
    varScope.addSVar("PackageOrTypeName_2_0", new InteropSDefT($Package$Or$Type$Name_2_0.instance, context));
    varScope.addSVar("PackageOrTypeName_1_0", new InteropSDefT($Package$Or$Type$Name_1_0.instance, context));
    varScope.addSVar("MethodName_2_0", new InteropSDefT($Method$Name_2_0.instance, context));
    varScope.addSVar("MethodName_1_0", new InteropSDefT($Method$Name_1_0.instance, context));
    varScope.addSVar("ExprName_2_0", new InteropSDefT($Expr$Name_2_0.instance, context));
    varScope.addSVar("ExprName_1_0", new InteropSDefT($Expr$Name_1_0.instance, context));
    varScope.addSVar("TypeName_2_0", new InteropSDefT($Type$Name_2_0.instance, context));
    varScope.addSVar("TypeName_1_0", new InteropSDefT($Type$Name_1_0.instance, context));
    varScope.addSVar("AmbName_2_0", new InteropSDefT($Amb$Name_2_0.instance, context));
    varScope.addSVar("AmbName_1_0", new InteropSDefT($Amb$Name_1_0.instance, context));
    varScope.addSVar("PackageName_1_0", new InteropSDefT($Package$Name_1_0.instance, context));
    varScope.addSVar("Double_0_0", new InteropSDefT($Double_0_0.instance, context));
    varScope.addSVar("Float_0_0", new InteropSDefT($Float_0_0.instance, context));
    varScope.addSVar("Char_0_0", new InteropSDefT($Char_0_0.instance, context));
    varScope.addSVar("Long_0_0", new InteropSDefT($Long_0_0.instance, context));
    varScope.addSVar("Int_0_0", new InteropSDefT($Int_0_0.instance, context));
    varScope.addSVar("Short_0_0", new InteropSDefT($Short_0_0.instance, context));
    varScope.addSVar("Byte_0_0", new InteropSDefT($Byte_0_0.instance, context));
    varScope.addSVar("Boolean_0_0", new InteropSDefT($Boolean_0_0.instance, context));
    varScope.addSVar("Null_0_0", new InteropSDefT($Null_0_0.instance, context));
    varScope.addSVar("Chars_1_0", new InteropSDefT($Chars_1_0.instance, context));
    varScope.addSVar("String_1_0", new InteropSDefT($String_1_0.instance, context));
    varScope.addSVar("Single_1_0", new InteropSDefT($Single_1_0.instance, context));
    varScope.addSVar("Char_1_0", new InteropSDefT($Char_1_0.instance, context));
    varScope.addSVar("False_0_0", new InteropSDefT($False_0_0.instance, context));
    varScope.addSVar("True_0_0", new InteropSDefT($True_0_0.instance, context));
    varScope.addSVar("Bool_1_0", new InteropSDefT($Bool_1_0.instance, context));
    varScope.addSVar("Float_1_0", new InteropSDefT($Float_1_0.instance, context));
    varScope.addSVar("Octa_1_0", new InteropSDefT($Octa_1_0.instance, context));
    varScope.addSVar("Hexa_1_0", new InteropSDefT($Hexa_1_0.instance, context));
    varScope.addSVar("Deci_1_0", new InteropSDefT($Deci_1_0.instance, context));
    varScope.addSVar("StrictFP_0_0", new InteropSDefT($Strict$F$P_0_0.instance, context));
    varScope.addSVar("Synchronized_0_0", new InteropSDefT($Synchronized_0_0.instance, context));
    varScope.addSVar("Volatile_0_0", new InteropSDefT($Volatile_0_0.instance, context));
    varScope.addSVar("Transient_0_0", new InteropSDefT($Transient_0_0.instance, context));
    varScope.addSVar("Native_0_0", new InteropSDefT($Native_0_0.instance, context));
    varScope.addSVar("Static_0_0", new InteropSDefT($Static_0_0.instance, context));
    varScope.addSVar("Final_0_0", new InteropSDefT($Final_0_0.instance, context));
    varScope.addSVar("Abstract_0_0", new InteropSDefT($Abstract_0_0.instance, context));
    varScope.addSVar("Protected_0_0", new InteropSDefT($Protected_0_0.instance, context));
    varScope.addSVar("Private_0_0", new InteropSDefT($Private_0_0.instance, context));
    varScope.addSVar("Public_0_0", new InteropSDefT($Public_0_0.instance, context));
    varScope.addSVar("Id_1_0", new InteropSDefT($Id_1_0.instance, context));
    varScope.addSVar("NamedEscape_1_0", new InteropSDefT($Named$Escape_1_0.instance, context));
  }

  private void registerLazy(org.spoofax.interpreter.core.IContext context, Context compiledContext, ClassLoader classLoader, org.spoofax.interpreter.core.VarScope varScope)
  { 
    compiledContext.registerComponent("renaming");
    renaming.init(compiledContext);
    varScope.addSVar("rename_java_0_3", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.rename_java_0_3", context));
    varScope.addSVar("do_rename_java_0_3", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.do_rename_java_0_3", context));
    varScope.addSVar("match_pkgs_java_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.match_pkgs_java_0_0", context));
    varScope.addSVar("CompilationUnit_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Compilation$Unit_3_0", context));
    varScope.addSVar("Semicolon_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Semicolon_0_0", context));
    varScope.addSVar("StaticImportOnDemandDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Static$Import$On$Demand$Dec_1_0", context));
    varScope.addSVar("StaticImportDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Static$Import$Dec_2_0", context));
    varScope.addSVar("TypeImportOnDemandDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Import$On$Demand$Dec_1_0", context));
    varScope.addSVar("TypeImportDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Import$Dec_1_0", context));
    varScope.addSVar("PackageDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Package$Dec_2_0", context));
    varScope.addSVar("ElemValArrayInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Elem$Val$Array$Init_1_0", context));
    varScope.addSVar("ElemValPair_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Elem$Val$Pair_2_0", context));
    varScope.addSVar("MarkerAnno_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Marker$Anno_1_0", context));
    varScope.addSVar("SingleElemAnno_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Single$Elem$Anno_2_0", context));
    varScope.addSVar("GenericMethod_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Generic$Method_3_0", context));
    varScope.addSVar("QSuperMethod_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Q$Super$Method_3_0", context));
    varScope.addSVar("SuperMethod_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Super$Method_2_0", context));
    varScope.addSVar("Method_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Method_3_0", context));
    varScope.addSVar("Method_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Method_1_0", context));
    varScope.addSVar("QSuperField_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Q$Super$Field_2_0", context));
    varScope.addSVar("SuperField_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Super$Field_1_0", context));
    varScope.addSVar("Field_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Field_2_0", context));
    varScope.addSVar("Dim_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Dim_1_0", context));
    varScope.addSVar("UnboundWld_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Unbound$Wld_1_0", context));
    varScope.addSVar("NewArray_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$New$Array_3_0", context));
    varScope.addSVar("ImplementsDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Implements$Dec_1_0", context));
    varScope.addSVar("SuperDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Super$Dec_1_0", context));
    varScope.addSVar("ClassDecHead_5_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Class$Dec$Head_5_0", context));
    varScope.addSVar("ClassBody_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Class$Body_1_0", context));
    varScope.addSVar("ClassDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Class$Dec_2_0", context));
    varScope.addSVar("ExtendsInterfaces_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Extends$Interfaces_1_0", context));
    varScope.addSVar("InterfaceDecHead_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Interface$Dec$Head_4_0", context));
    varScope.addSVar("InterfaceDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Interface$Dec_2_0", context));
    varScope.addSVar("DefaultVal_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Default$Val_1_0", context));
    varScope.addSVar("AnnoMethodDec_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Anno$Method$Dec_4_0", context));
    varScope.addSVar("AnnoDecHead_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Anno$Dec$Head_2_0", context));
    varScope.addSVar("AnnoDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Anno$Dec_2_0", context));
    varScope.addSVar("DeprAbstractMethodDec_7_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Depr$Abstract$Method$Dec_7_0", context));
    varScope.addSVar("AbstractMethodDec_6_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Abstract$Method$Dec_6_0", context));
    varScope.addSVar("ConstantDec_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Constant$Dec_3_0", context));
    varScope.addSVar("EnumBodyDecs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Enum$Body$Decs_1_0", context));
    varScope.addSVar("EnumConst_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Enum$Const_3_0", context));
    varScope.addSVar("EnumBody_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Enum$Body_2_0", context));
    varScope.addSVar("EnumDecHead_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Enum$Dec$Head_3_0", context));
    varScope.addSVar("EnumDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Enum$Dec_2_0", context));
    varScope.addSVar("QSuperConstrInv_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Q$Super$Constr$Inv_3_0", context));
    varScope.addSVar("SuperConstrInv_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Super$Constr$Inv_2_0", context));
    varScope.addSVar("AltConstrInv_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Alt$Constr$Inv_2_0", context));
    varScope.addSVar("ConstrBody_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Constr$Body_2_0", context));
    varScope.addSVar("ConstrDecHead_5_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Constr$Dec$Head_5_0", context));
    varScope.addSVar("ConstrDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Constr$Dec_2_0", context));
    varScope.addSVar("StaticInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Static$Init_1_0", context));
    varScope.addSVar("InstanceInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Instance$Init_1_0", context));
    varScope.addSVar("NoMethodBody_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$No$Method$Body_0_0", context));
    varScope.addSVar("ThrowsDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Throws$Dec_1_0", context));
    varScope.addSVar("VarArityParam_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Var$Arity$Param_3_0", context));
    varScope.addSVar("Param_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Param_3_0", context));
    varScope.addSVar("Void_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Void_0_0", context));
    varScope.addSVar("DeprMethodDecHead_7_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Depr$Method$Dec$Head_7_0", context));
    varScope.addSVar("MethodDecHead_6_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Method$Dec$Head_6_0", context));
    varScope.addSVar("MethodDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Method$Dec_2_0", context));
    varScope.addSVar("ClassDecStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Class$Dec$Stm_1_0", context));
    varScope.addSVar("Block_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Block_1_0", context));
    varScope.addSVar("Default_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Default_0_0", context));
    varScope.addSVar("Case_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Case_1_0", context));
    varScope.addSVar("SwitchGroup_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Switch$Group_2_0", context));
    varScope.addSVar("SwitchBlock_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Switch$Block_2_0", context));
    varScope.addSVar("Try_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Try_3_0", context));
    varScope.addSVar("Try_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Try_2_0", context));
    varScope.addSVar("Synchronized_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Synchronized_2_0", context));
    varScope.addSVar("Throw_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Throw_1_0", context));
    varScope.addSVar("Return_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Return_1_0", context));
    varScope.addSVar("Continue_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Continue_1_0", context));
    varScope.addSVar("Break_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Break_1_0", context));
    varScope.addSVar("ForEach_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$For$Each_3_0", context));
    varScope.addSVar("For_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$For_4_0", context));
    varScope.addSVar("DoWhile_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Do$While_2_0", context));
    varScope.addSVar("While_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$While_2_0", context));
    varScope.addSVar("Switch_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Switch_2_0", context));
    varScope.addSVar("AssertStm_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assert$Stm_2_0", context));
    varScope.addSVar("AssertStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assert$Stm_1_0", context));
    varScope.addSVar("If_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$If_3_0", context));
    varScope.addSVar("If_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$If_2_0", context));
    varScope.addSVar("ExprStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Expr$Stm_1_0", context));
    varScope.addSVar("Labeled_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Labeled_2_0", context));
    varScope.addSVar("Empty_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Empty_0_0", context));
    varScope.addSVar("LocalVarDec_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Local$Var$Dec_3_0", context));
    varScope.addSVar("LocalVarDecStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Local$Var$Dec$Stm_1_0", context));
    varScope.addSVar("Dim_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Dim_0_0", context));
    varScope.addSVar("ArrayVarDecId_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Array$Var$Dec$Id_2_0", context));
    varScope.addSVar("VarDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Var$Dec_2_0", context));
    varScope.addSVar("VarDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Var$Dec_1_0", context));
    varScope.addSVar("FieldDec_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Field$Dec_3_0", context));
    varScope.addSVar("ArrayInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Array$Init_1_0", context));
    varScope.addSVar("VoidClass_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Void$Class_0_0", context));
    varScope.addSVar("Class_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Class_1_0", context));
    varScope.addSVar("AssignOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Or_2_0", context));
    varScope.addSVar("AssignExcOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Exc$Or_2_0", context));
    varScope.addSVar("AssignAnd_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$And_2_0", context));
    varScope.addSVar("AssignURightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$U$Right$Shift_2_0", context));
    varScope.addSVar("AssignRightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Right$Shift_2_0", context));
    varScope.addSVar("AssignLeftShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Left$Shift_2_0", context));
    varScope.addSVar("AssignMinus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Minus_2_0", context));
    varScope.addSVar("AssignPlus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Plus_2_0", context));
    varScope.addSVar("AssignRemain_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Remain_2_0", context));
    varScope.addSVar("AssignDiv_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Div_2_0", context));
    varScope.addSVar("AssignMul_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign$Mul_2_0", context));
    varScope.addSVar("Assign_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Assign_2_0", context));
    varScope.addSVar("Or_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Or_2_0", context));
    varScope.addSVar("ExcOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Exc$Or_2_0", context));
    varScope.addSVar("And_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$And_2_0", context));
    varScope.addSVar("LazyOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Lazy$Or_2_0", context));
    varScope.addSVar("LazyAnd_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Lazy$And_2_0", context));
    varScope.addSVar("NotEq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Not$Eq_2_0", context));
    varScope.addSVar("Eq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Eq_2_0", context));
    varScope.addSVar("GtEq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Gt$Eq_2_0", context));
    varScope.addSVar("LtEq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Lt$Eq_2_0", context));
    varScope.addSVar("Gt_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Gt_2_0", context));
    varScope.addSVar("Lt_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Lt_2_0", context));
    varScope.addSVar("URightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$U$Right$Shift_2_0", context));
    varScope.addSVar("RightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Right$Shift_2_0", context));
    varScope.addSVar("LeftShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Left$Shift_2_0", context));
    varScope.addSVar("Minus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Minus_2_0", context));
    varScope.addSVar("Plus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Plus_2_0", context));
    varScope.addSVar("Remain_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Remain_2_0", context));
    varScope.addSVar("Div_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Div_2_0", context));
    varScope.addSVar("Mul_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Mul_2_0", context));
    varScope.addSVar("InstanceOf_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Instance$Of_2_0", context));
    varScope.addSVar("CastRef_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Cast$Ref_2_0", context));
    varScope.addSVar("CastPrim_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Cast$Prim_2_0", context));
    varScope.addSVar("Not_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Not_1_0", context));
    varScope.addSVar("Complement_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Complement_1_0", context));
    varScope.addSVar("PreDecr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Pre$Decr_1_0", context));
    varScope.addSVar("PreIncr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Pre$Incr_1_0", context));
    varScope.addSVar("Minus_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Minus_1_0", context));
    varScope.addSVar("Plus_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Plus_1_0", context));
    varScope.addSVar("PostDecr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Post$Decr_1_0", context));
    varScope.addSVar("PostIncr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Post$Incr_1_0", context));
    varScope.addSVar("Invoke_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Invoke_2_0", context));
    varScope.addSVar("QNewInstance_6_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Q$New$Instance_6_0", context));
    varScope.addSVar("NewInstance_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$New$Instance_4_0", context));
    varScope.addSVar("QThis_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Q$This_1_0", context));
    varScope.addSVar("This_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$This_0_0", context));
    varScope.addSVar("Lit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Lit_1_0", context));
    varScope.addSVar("ArrayType_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Array$Type_1_0", context));
    varScope.addSVar("TypeVar_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Var_1_0", context));
    varScope.addSVar("Member_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Member_3_0", context));
    varScope.addSVar("InterfaceType_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Interface$Type_2_0", context));
    varScope.addSVar("ClassType_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Class$Type_2_0", context));
    varScope.addSVar("ClassOrInterfaceType_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Class$Or$Interface$Type_2_0", context));
    varScope.addSVar("TypeParams_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Params_1_0", context));
    varScope.addSVar("TypeBound_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Bound_1_0", context));
    varScope.addSVar("TypeParam_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Param_2_0", context));
    varScope.addSVar("WildcardLowerBound_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Wildcard$Lower$Bound_1_0", context));
    varScope.addSVar("WildcardUpperBound_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Wildcard$Upper$Bound_1_0", context));
    varScope.addSVar("Wildcard_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Wildcard_1_0", context));
    varScope.addSVar("TypeArgs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Args_1_0", context));
    varScope.addSVar("PackageOrTypeName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Package$Or$Type$Name_2_0", context));
    varScope.addSVar("PackageOrTypeName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Package$Or$Type$Name_1_0", context));
    varScope.addSVar("MethodName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Method$Name_2_0", context));
    varScope.addSVar("MethodName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Method$Name_1_0", context));
    varScope.addSVar("ExprName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Expr$Name_2_0", context));
    varScope.addSVar("ExprName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Expr$Name_1_0", context));
    varScope.addSVar("TypeName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Name_2_0", context));
    varScope.addSVar("TypeName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Type$Name_1_0", context));
    varScope.addSVar("AmbName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Amb$Name_2_0", context));
    varScope.addSVar("AmbName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Amb$Name_1_0", context));
    varScope.addSVar("PackageName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Package$Name_1_0", context));
    varScope.addSVar("Double_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Double_0_0", context));
    varScope.addSVar("Float_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Float_0_0", context));
    varScope.addSVar("Char_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Char_0_0", context));
    varScope.addSVar("Long_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Long_0_0", context));
    varScope.addSVar("Int_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Int_0_0", context));
    varScope.addSVar("Short_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Short_0_0", context));
    varScope.addSVar("Byte_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Byte_0_0", context));
    varScope.addSVar("Boolean_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Boolean_0_0", context));
    varScope.addSVar("Null_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Null_0_0", context));
    varScope.addSVar("Chars_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Chars_1_0", context));
    varScope.addSVar("String_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$String_1_0", context));
    varScope.addSVar("Single_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Single_1_0", context));
    varScope.addSVar("Char_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Char_1_0", context));
    varScope.addSVar("False_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$False_0_0", context));
    varScope.addSVar("True_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$True_0_0", context));
    varScope.addSVar("Bool_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Bool_1_0", context));
    varScope.addSVar("Float_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Float_1_0", context));
    varScope.addSVar("Octa_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Octa_1_0", context));
    varScope.addSVar("Hexa_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Hexa_1_0", context));
    varScope.addSVar("Deci_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Deci_1_0", context));
    varScope.addSVar("StrictFP_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Strict$F$P_0_0", context));
    varScope.addSVar("Synchronized_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Synchronized_0_0", context));
    varScope.addSVar("Volatile_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Volatile_0_0", context));
    varScope.addSVar("Transient_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Transient_0_0", context));
    varScope.addSVar("Native_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Native_0_0", context));
    varScope.addSVar("Static_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Static_0_0", context));
    varScope.addSVar("Final_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Final_0_0", context));
    varScope.addSVar("Abstract_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Abstract_0_0", context));
    varScope.addSVar("Protected_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Protected_0_0", context));
    varScope.addSVar("Private_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Private_0_0", context));
    varScope.addSVar("Public_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Public_0_0", context));
    varScope.addSVar("Id_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Id_1_0", context));
    varScope.addSVar("NamedEscape_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.renaming.$Named$Escape_1_0", context));
  }
}