package org.sugarj.driver.transformations.renaming;

import org.strategoxt.stratego_lib.*;
import org.strategoxt.lang.*;
import org.spoofax.interpreter.terms.*;
import static org.strategoxt.lang.Term.*;
import org.spoofax.interpreter.library.AbstractPrimitive;
import java.util.ArrayList;
import java.lang.ref.WeakReference;

@SuppressWarnings("unused") public class InteropRegisterer extends org.strategoxt.lang.InteropRegisterer 
{ 
  @Override public void register(org.spoofax.interpreter.core.IContext context, Context compiledContext)
  { 
    register(context, compiledContext, context.getVarScope());
  }

  @Override public void registerLazy(org.spoofax.interpreter.core.IContext context, Context compiledContext, ClassLoader classLoader)
  { 
    registerLazy(context, compiledContext, classLoader, context.getVarScope());
  }

  private void register(org.spoofax.interpreter.core.IContext context, Context compiledContext, org.spoofax.interpreter.core.VarScope varScope)
  { 
    compiledContext.registerComponent("renaming");
    renaming.init(compiledContext);
    varScope.addSVar("rename_rules_0_2", new InteropSDefT(rename_rules_0_2.instance, context));
    varScope.addSVar("rename_rule_0_2", new InteropSDefT(rename_rule_0_2.instance, context));
    varScope.addSVar("apply_renaming_0_3", new InteropSDefT(apply_renaming_0_3.instance, context));
    varScope.addSVar("rename_java_0_3", new InteropSDefT(rename_java_0_3.instance, context));
    varScope.addSVar("rename_sugardec_0_2", new InteropSDefT(rename_sugardec_0_2.instance, context));
    varScope.addSVar("rename_modeldec_0_2", new InteropSDefT(rename_modeldec_0_2.instance, context));
    varScope.addSVar("rename_editordec_0_2", new InteropSDefT(rename_editordec_0_2.instance, context));
    varScope.addSVar("do_rename_java_0_3", new InteropSDefT(do_rename_java_0_3.instance, context));
    varScope.addSVar("match_pkgs_java_0_0", new InteropSDefT(match_pkgs_java_0_0.instance, context));
    varScope.addSVar("ToModelTerm_1_0", new InteropSDefT($To$Model$Term_1_0.instance, context));
    varScope.addSVar("TransApp_2_0", new InteropSDefT($Trans$App_2_0.instance, context));
    varScope.addSVar("transformation_elem_1_0", new InteropSDefT(transformation_elem_1_0.instance, context));
    varScope.addSVar("grammar_elem_1_0", new InteropSDefT(grammar_elem_1_0.instance, context));
    varScope.addSVar("Desugarings_1_0", new InteropSDefT($Desugarings_1_0.instance, context));
    varScope.addSVar("InjectDesugaring_4_0", new InteropSDefT($Inject$Desugaring_4_0.instance, context));
    varScope.addSVar("PureDesugaring_1_0", new InteropSDefT($Pure$Desugaring_1_0.instance, context));
    varScope.addSVar("CompilationUnit_3_0", new InteropSDefT($Compilation$Unit_3_0.instance, context));
    varScope.addSVar("CompileError_2_0", new InteropSDefT($Compile$Error_2_0.instance, context));
    varScope.addSVar("SugarBody_1_0", new InteropSDefT($Sugar$Body_1_0.instance, context));
    varScope.addSVar("SugarDec_2_0", new InteropSDefT($Sugar$Dec_2_0.instance, context));
    varScope.addSVar("SugarDecHead_2_0", new InteropSDefT($Sugar$Dec$Head_2_0.instance, context));
    varScope.addSVar("EditorServicesDec_2_0", new InteropSDefT($Editor$Services$Dec_2_0.instance, context));
    varScope.addSVar("EditorServicesDecHead_2_0", new InteropSDefT($Editor$Services$Dec$Head_2_0.instance, context));
    varScope.addSVar("EditorServicesBody_1_0", new InteropSDefT($Editor$Services$Body_1_0.instance, context));
    varScope.addSVar("ChecksDec_2_0", new InteropSDefT($Checks$Dec_2_0.instance, context));
    varScope.addSVar("ChecksDecHead_2_0", new InteropSDefT($Checks$Dec$Head_2_0.instance, context));
    varScope.addSVar("ChecksBody_1_0", new InteropSDefT($Checks$Body_1_0.instance, context));
    varScope.addSVar("ModelDec_2_0", new InteropSDefT($Model$Dec_2_0.instance, context));
    varScope.addSVar("ModelDecHead_3_0", new InteropSDefT($Model$Dec$Head_3_0.instance, context));
    varScope.addSVar("ModelBody_1_0", new InteropSDefT($Model$Body_1_0.instance, context));
    varScope.addSVar("TransDec_2_0", new InteropSDefT($Trans$Dec_2_0.instance, context));
    varScope.addSVar("TransDecHead_2_0", new InteropSDefT($Trans$Dec$Head_2_0.instance, context));
    varScope.addSVar("TransBody_1_0", new InteropSDefT($Trans$Body_1_0.instance, context));
    varScope.addSVar("TransImportDec_2_0", new InteropSDefT($Trans$Import$Dec_2_0.instance, context));
    varScope.addSVar("TypeImportAsDec_2_0", new InteropSDefT($Type$Import$As$Dec_2_0.instance, context));
    varScope.addSVar("ImportAs_1_0", new InteropSDefT($Import$As_1_0.instance, context));
    varScope.addSVar("Semicolon_0_0", new InteropSDefT($Semicolon_0_0.instance, context));
    varScope.addSVar("StaticImportOnDemandDec_1_0", new InteropSDefT($Static$Import$On$Demand$Dec_1_0.instance, context));
    varScope.addSVar("StaticImportDec_2_0", new InteropSDefT($Static$Import$Dec_2_0.instance, context));
    varScope.addSVar("TypeImportOnDemandDec_1_0", new InteropSDefT($Type$Import$On$Demand$Dec_1_0.instance, context));
    varScope.addSVar("TypeImportDec_1_0", new InteropSDefT($Type$Import$Dec_1_0.instance, context));
    varScope.addSVar("PackageDec_2_0", new InteropSDefT($Package$Dec_2_0.instance, context));
    varScope.addSVar("ElemValArrayInit_1_0", new InteropSDefT($Elem$Val$Array$Init_1_0.instance, context));
    varScope.addSVar("ElemValPair_2_0", new InteropSDefT($Elem$Val$Pair_2_0.instance, context));
    varScope.addSVar("MarkerAnno_1_0", new InteropSDefT($Marker$Anno_1_0.instance, context));
    varScope.addSVar("SingleElemAnno_2_0", new InteropSDefT($Single$Elem$Anno_2_0.instance, context));
    varScope.addSVar("GenericMethod_3_0", new InteropSDefT($Generic$Method_3_0.instance, context));
    varScope.addSVar("QSuperMethod_3_0", new InteropSDefT($Q$Super$Method_3_0.instance, context));
    varScope.addSVar("SuperMethod_2_0", new InteropSDefT($Super$Method_2_0.instance, context));
    varScope.addSVar("Method_3_0", new InteropSDefT($Method_3_0.instance, context));
    varScope.addSVar("Method_1_0", new InteropSDefT($Method_1_0.instance, context));
    varScope.addSVar("QSuperField_2_0", new InteropSDefT($Q$Super$Field_2_0.instance, context));
    varScope.addSVar("SuperField_1_0", new InteropSDefT($Super$Field_1_0.instance, context));
    varScope.addSVar("Field_2_0", new InteropSDefT($Field_2_0.instance, context));
    varScope.addSVar("Dim_1_0", new InteropSDefT($Dim_1_0.instance, context));
    varScope.addSVar("UnboundWld_1_0", new InteropSDefT($Unbound$Wld_1_0.instance, context));
    varScope.addSVar("NewArray_3_0", new InteropSDefT($New$Array_3_0.instance, context));
    varScope.addSVar("ImplementsDec_1_0", new InteropSDefT($Implements$Dec_1_0.instance, context));
    varScope.addSVar("SuperDec_1_0", new InteropSDefT($Super$Dec_1_0.instance, context));
    varScope.addSVar("ClassDecHead_5_0", new InteropSDefT($Class$Dec$Head_5_0.instance, context));
    varScope.addSVar("ClassBody_1_0", new InteropSDefT($Class$Body_1_0.instance, context));
    varScope.addSVar("ClassDec_2_0", new InteropSDefT($Class$Dec_2_0.instance, context));
    varScope.addSVar("ExtendsInterfaces_1_0", new InteropSDefT($Extends$Interfaces_1_0.instance, context));
    varScope.addSVar("InterfaceDecHead_4_0", new InteropSDefT($Interface$Dec$Head_4_0.instance, context));
    varScope.addSVar("InterfaceDec_2_0", new InteropSDefT($Interface$Dec_2_0.instance, context));
    varScope.addSVar("DefaultVal_1_0", new InteropSDefT($Default$Val_1_0.instance, context));
    varScope.addSVar("AnnoMethodDec_4_0", new InteropSDefT($Anno$Method$Dec_4_0.instance, context));
    varScope.addSVar("AnnoDecHead_2_0", new InteropSDefT($Anno$Dec$Head_2_0.instance, context));
    varScope.addSVar("AnnoDec_2_0", new InteropSDefT($Anno$Dec_2_0.instance, context));
    varScope.addSVar("DeprAbstractMethodDec_7_0", new InteropSDefT($Depr$Abstract$Method$Dec_7_0.instance, context));
    varScope.addSVar("AbstractMethodDec_6_0", new InteropSDefT($Abstract$Method$Dec_6_0.instance, context));
    varScope.addSVar("ConstantDec_3_0", new InteropSDefT($Constant$Dec_3_0.instance, context));
    varScope.addSVar("EnumBodyDecs_1_0", new InteropSDefT($Enum$Body$Decs_1_0.instance, context));
    varScope.addSVar("EnumConst_3_0", new InteropSDefT($Enum$Const_3_0.instance, context));
    varScope.addSVar("EnumBody_2_0", new InteropSDefT($Enum$Body_2_0.instance, context));
    varScope.addSVar("EnumDecHead_3_0", new InteropSDefT($Enum$Dec$Head_3_0.instance, context));
    varScope.addSVar("EnumDec_2_0", new InteropSDefT($Enum$Dec_2_0.instance, context));
    varScope.addSVar("QSuperConstrInv_3_0", new InteropSDefT($Q$Super$Constr$Inv_3_0.instance, context));
    varScope.addSVar("SuperConstrInv_2_0", new InteropSDefT($Super$Constr$Inv_2_0.instance, context));
    varScope.addSVar("AltConstrInv_2_0", new InteropSDefT($Alt$Constr$Inv_2_0.instance, context));
    varScope.addSVar("ConstrBody_2_0", new InteropSDefT($Constr$Body_2_0.instance, context));
    varScope.addSVar("ConstrDecHead_5_0", new InteropSDefT($Constr$Dec$Head_5_0.instance, context));
    varScope.addSVar("ConstrDec_2_0", new InteropSDefT($Constr$Dec_2_0.instance, context));
    varScope.addSVar("StaticInit_1_0", new InteropSDefT($Static$Init_1_0.instance, context));
    varScope.addSVar("InstanceInit_1_0", new InteropSDefT($Instance$Init_1_0.instance, context));
    varScope.addSVar("NoMethodBody_0_0", new InteropSDefT($No$Method$Body_0_0.instance, context));
    varScope.addSVar("ThrowsDec_1_0", new InteropSDefT($Throws$Dec_1_0.instance, context));
    varScope.addSVar("VarArityParam_3_0", new InteropSDefT($Var$Arity$Param_3_0.instance, context));
    varScope.addSVar("Param_3_0", new InteropSDefT($Param_3_0.instance, context));
    varScope.addSVar("Void_0_0", new InteropSDefT($Void_0_0.instance, context));
    varScope.addSVar("DeprMethodDecHead_7_0", new InteropSDefT($Depr$Method$Dec$Head_7_0.instance, context));
    varScope.addSVar("MethodDecHead_6_0", new InteropSDefT($Method$Dec$Head_6_0.instance, context));
    varScope.addSVar("MethodDec_2_0", new InteropSDefT($Method$Dec_2_0.instance, context));
    varScope.addSVar("ClassDecStm_1_0", new InteropSDefT($Class$Dec$Stm_1_0.instance, context));
    varScope.addSVar("Block_1_0", new InteropSDefT($Block_1_0.instance, context));
    varScope.addSVar("Default_0_0", new InteropSDefT($Default_0_0.instance, context));
    varScope.addSVar("Case_1_0", new InteropSDefT($Case_1_0.instance, context));
    varScope.addSVar("SwitchGroup_2_0", new InteropSDefT($Switch$Group_2_0.instance, context));
    varScope.addSVar("SwitchBlock_2_0", new InteropSDefT($Switch$Block_2_0.instance, context));
    varScope.addSVar("Try_3_0", new InteropSDefT($Try_3_0.instance, context));
    varScope.addSVar("Try_2_0", new InteropSDefT($Try_2_0.instance, context));
    varScope.addSVar("Synchronized_2_0", new InteropSDefT($Synchronized_2_0.instance, context));
    varScope.addSVar("Throw_1_0", new InteropSDefT($Throw_1_0.instance, context));
    varScope.addSVar("Return_1_0", new InteropSDefT($Return_1_0.instance, context));
    varScope.addSVar("Continue_1_0", new InteropSDefT($Continue_1_0.instance, context));
    varScope.addSVar("Break_1_0", new InteropSDefT($Break_1_0.instance, context));
    varScope.addSVar("ForEach_3_0", new InteropSDefT($For$Each_3_0.instance, context));
    varScope.addSVar("For_4_0", new InteropSDefT($For_4_0.instance, context));
    varScope.addSVar("DoWhile_2_0", new InteropSDefT($Do$While_2_0.instance, context));
    varScope.addSVar("While_2_0", new InteropSDefT($While_2_0.instance, context));
    varScope.addSVar("Switch_2_0", new InteropSDefT($Switch_2_0.instance, context));
    varScope.addSVar("AssertStm_2_0", new InteropSDefT($Assert$Stm_2_0.instance, context));
    varScope.addSVar("AssertStm_1_0", new InteropSDefT($Assert$Stm_1_0.instance, context));
    varScope.addSVar("If_3_0", new InteropSDefT($If_3_0.instance, context));
    varScope.addSVar("If_2_0", new InteropSDefT($If_2_0.instance, context));
    varScope.addSVar("ExprStm_1_0", new InteropSDefT($Expr$Stm_1_0.instance, context));
    varScope.addSVar("Labeled_2_0", new InteropSDefT($Labeled_2_0.instance, context));
    varScope.addSVar("Empty_0_0", new InteropSDefT($Empty_0_0.instance, context));
    varScope.addSVar("LocalVarDec_3_0", new InteropSDefT($Local$Var$Dec_3_0.instance, context));
    varScope.addSVar("LocalVarDecStm_1_0", new InteropSDefT($Local$Var$Dec$Stm_1_0.instance, context));
    varScope.addSVar("Dim_0_0", new InteropSDefT($Dim_0_0.instance, context));
    varScope.addSVar("ArrayVarDecId_2_0", new InteropSDefT($Array$Var$Dec$Id_2_0.instance, context));
    varScope.addSVar("VarDec_2_0", new InteropSDefT($Var$Dec_2_0.instance, context));
    varScope.addSVar("VarDec_1_0", new InteropSDefT($Var$Dec_1_0.instance, context));
    varScope.addSVar("FieldDec_3_0", new InteropSDefT($Field$Dec_3_0.instance, context));
    varScope.addSVar("ArrayInit_1_0", new InteropSDefT($Array$Init_1_0.instance, context));
    varScope.addSVar("VoidClass_0_0", new InteropSDefT($Void$Class_0_0.instance, context));
    varScope.addSVar("Class_1_0", new InteropSDefT($Class_1_0.instance, context));
    varScope.addSVar("AssignOr_2_0", new InteropSDefT($Assign$Or_2_0.instance, context));
    varScope.addSVar("AssignExcOr_2_0", new InteropSDefT($Assign$Exc$Or_2_0.instance, context));
    varScope.addSVar("AssignAnd_2_0", new InteropSDefT($Assign$And_2_0.instance, context));
    varScope.addSVar("AssignURightShift_2_0", new InteropSDefT($Assign$U$Right$Shift_2_0.instance, context));
    varScope.addSVar("AssignRightShift_2_0", new InteropSDefT($Assign$Right$Shift_2_0.instance, context));
    varScope.addSVar("AssignLeftShift_2_0", new InteropSDefT($Assign$Left$Shift_2_0.instance, context));
    varScope.addSVar("AssignMinus_2_0", new InteropSDefT($Assign$Minus_2_0.instance, context));
    varScope.addSVar("AssignPlus_2_0", new InteropSDefT($Assign$Plus_2_0.instance, context));
    varScope.addSVar("AssignRemain_2_0", new InteropSDefT($Assign$Remain_2_0.instance, context));
    varScope.addSVar("AssignDiv_2_0", new InteropSDefT($Assign$Div_2_0.instance, context));
    varScope.addSVar("AssignMul_2_0", new InteropSDefT($Assign$Mul_2_0.instance, context));
    varScope.addSVar("Assign_2_0", new InteropSDefT($Assign_2_0.instance, context));
    varScope.addSVar("Or_2_0", new InteropSDefT($Or_2_0.instance, context));
    varScope.addSVar("ExcOr_2_0", new InteropSDefT($Exc$Or_2_0.instance, context));
    varScope.addSVar("And_2_0", new InteropSDefT($And_2_0.instance, context));
    varScope.addSVar("LazyOr_2_0", new InteropSDefT($Lazy$Or_2_0.instance, context));
    varScope.addSVar("LazyAnd_2_0", new InteropSDefT($Lazy$And_2_0.instance, context));
    varScope.addSVar("NotEq_2_0", new InteropSDefT($Not$Eq_2_0.instance, context));
    varScope.addSVar("Eq_2_0", new InteropSDefT($Eq_2_0.instance, context));
    varScope.addSVar("GtEq_2_0", new InteropSDefT($Gt$Eq_2_0.instance, context));
    varScope.addSVar("LtEq_2_0", new InteropSDefT($Lt$Eq_2_0.instance, context));
    varScope.addSVar("Gt_2_0", new InteropSDefT($Gt_2_0.instance, context));
    varScope.addSVar("Lt_2_0", new InteropSDefT($Lt_2_0.instance, context));
    varScope.addSVar("URightShift_2_0", new InteropSDefT($U$Right$Shift_2_0.instance, context));
    varScope.addSVar("RightShift_2_0", new InteropSDefT($Right$Shift_2_0.instance, context));
    varScope.addSVar("LeftShift_2_0", new InteropSDefT($Left$Shift_2_0.instance, context));
    varScope.addSVar("Minus_2_0", new InteropSDefT($Minus_2_0.instance, context));
    varScope.addSVar("Plus_2_0", new InteropSDefT($Plus_2_0.instance, context));
    varScope.addSVar("Remain_2_0", new InteropSDefT($Remain_2_0.instance, context));
    varScope.addSVar("Div_2_0", new InteropSDefT($Div_2_0.instance, context));
    varScope.addSVar("Mul_2_0", new InteropSDefT($Mul_2_0.instance, context));
    varScope.addSVar("InstanceOf_2_0", new InteropSDefT($Instance$Of_2_0.instance, context));
    varScope.addSVar("CastRef_2_0", new InteropSDefT($Cast$Ref_2_0.instance, context));
    varScope.addSVar("CastPrim_2_0", new InteropSDefT($Cast$Prim_2_0.instance, context));
    varScope.addSVar("Not_1_0", new InteropSDefT($Not_1_0.instance, context));
    varScope.addSVar("Complement_1_0", new InteropSDefT($Complement_1_0.instance, context));
    varScope.addSVar("PreDecr_1_0", new InteropSDefT($Pre$Decr_1_0.instance, context));
    varScope.addSVar("PreIncr_1_0", new InteropSDefT($Pre$Incr_1_0.instance, context));
    varScope.addSVar("Minus_1_0", new InteropSDefT($Minus_1_0.instance, context));
    varScope.addSVar("Plus_1_0", new InteropSDefT($Plus_1_0.instance, context));
    varScope.addSVar("PostDecr_1_0", new InteropSDefT($Post$Decr_1_0.instance, context));
    varScope.addSVar("PostIncr_1_0", new InteropSDefT($Post$Incr_1_0.instance, context));
    varScope.addSVar("Invoke_2_0", new InteropSDefT($Invoke_2_0.instance, context));
    varScope.addSVar("QNewInstance_6_0", new InteropSDefT($Q$New$Instance_6_0.instance, context));
    varScope.addSVar("NewInstance_4_0", new InteropSDefT($New$Instance_4_0.instance, context));
    varScope.addSVar("QThis_1_0", new InteropSDefT($Q$This_1_0.instance, context));
    varScope.addSVar("This_0_0", new InteropSDefT($This_0_0.instance, context));
    varScope.addSVar("Lit_1_0", new InteropSDefT($Lit_1_0.instance, context));
    varScope.addSVar("ArrayType_1_0", new InteropSDefT($Array$Type_1_0.instance, context));
    varScope.addSVar("TypeVar_1_0", new InteropSDefT($Type$Var_1_0.instance, context));
    varScope.addSVar("Member_3_0", new InteropSDefT($Member_3_0.instance, context));
    varScope.addSVar("InterfaceType_2_0", new InteropSDefT($Interface$Type_2_0.instance, context));
    varScope.addSVar("ClassType_2_0", new InteropSDefT($Class$Type_2_0.instance, context));
    varScope.addSVar("ClassOrInterfaceType_2_0", new InteropSDefT($Class$Or$Interface$Type_2_0.instance, context));
    varScope.addSVar("TypeParams_1_0", new InteropSDefT($Type$Params_1_0.instance, context));
    varScope.addSVar("TypeBound_1_0", new InteropSDefT($Type$Bound_1_0.instance, context));
    varScope.addSVar("TypeParam_2_0", new InteropSDefT($Type$Param_2_0.instance, context));
    varScope.addSVar("WildcardLowerBound_1_0", new InteropSDefT($Wildcard$Lower$Bound_1_0.instance, context));
    varScope.addSVar("WildcardUpperBound_1_0", new InteropSDefT($Wildcard$Upper$Bound_1_0.instance, context));
    varScope.addSVar("Wildcard_1_0", new InteropSDefT($Wildcard_1_0.instance, context));
    varScope.addSVar("TypeArgs_1_0", new InteropSDefT($Type$Args_1_0.instance, context));
    varScope.addSVar("PackageOrTypeName_2_0", new InteropSDefT($Package$Or$Type$Name_2_0.instance, context));
    varScope.addSVar("PackageOrTypeName_1_0", new InteropSDefT($Package$Or$Type$Name_1_0.instance, context));
    varScope.addSVar("MethodName_2_0", new InteropSDefT($Method$Name_2_0.instance, context));
    varScope.addSVar("MethodName_1_0", new InteropSDefT($Method$Name_1_0.instance, context));
    varScope.addSVar("ExprName_2_0", new InteropSDefT($Expr$Name_2_0.instance, context));
    varScope.addSVar("ExprName_1_0", new InteropSDefT($Expr$Name_1_0.instance, context));
    varScope.addSVar("TypeName_2_0", new InteropSDefT($Type$Name_2_0.instance, context));
    varScope.addSVar("TypeName_1_0", new InteropSDefT($Type$Name_1_0.instance, context));
    varScope.addSVar("AmbName_2_0", new InteropSDefT($Amb$Name_2_0.instance, context));
    varScope.addSVar("AmbName_1_0", new InteropSDefT($Amb$Name_1_0.instance, context));
    varScope.addSVar("PackageName_1_0", new InteropSDefT($Package$Name_1_0.instance, context));
    varScope.addSVar("Double_0_0", new InteropSDefT($Double_0_0.instance, context));
    varScope.addSVar("Float_0_0", new InteropSDefT($Float_0_0.instance, context));
    varScope.addSVar("Char_0_0", new InteropSDefT($Char_0_0.instance, context));
    varScope.addSVar("Long_0_0", new InteropSDefT($Long_0_0.instance, context));
    varScope.addSVar("Int_0_0", new InteropSDefT($Int_0_0.instance, context));
    varScope.addSVar("Short_0_0", new InteropSDefT($Short_0_0.instance, context));
    varScope.addSVar("Byte_0_0", new InteropSDefT($Byte_0_0.instance, context));
    varScope.addSVar("Boolean_0_0", new InteropSDefT($Boolean_0_0.instance, context));
    varScope.addSVar("Null_0_0", new InteropSDefT($Null_0_0.instance, context));
    varScope.addSVar("Chars_1_0", new InteropSDefT($Chars_1_0.instance, context));
    varScope.addSVar("String_1_0", new InteropSDefT($String_1_0.instance, context));
    varScope.addSVar("Single_1_0", new InteropSDefT($Single_1_0.instance, context));
    varScope.addSVar("Char_1_0", new InteropSDefT($Char_1_0.instance, context));
    varScope.addSVar("False_0_0", new InteropSDefT($False_0_0.instance, context));
    varScope.addSVar("True_0_0", new InteropSDefT($True_0_0.instance, context));
    varScope.addSVar("Bool_1_0", new InteropSDefT($Bool_1_0.instance, context));
    varScope.addSVar("Float_1_0", new InteropSDefT($Float_1_0.instance, context));
    varScope.addSVar("Octa_1_0", new InteropSDefT($Octa_1_0.instance, context));
    varScope.addSVar("Hexa_1_0", new InteropSDefT($Hexa_1_0.instance, context));
    varScope.addSVar("Deci_1_0", new InteropSDefT($Deci_1_0.instance, context));
    varScope.addSVar("StrictFP_0_0", new InteropSDefT($Strict$F$P_0_0.instance, context));
    varScope.addSVar("Synchronized_0_0", new InteropSDefT($Synchronized_0_0.instance, context));
    varScope.addSVar("Volatile_0_0", new InteropSDefT($Volatile_0_0.instance, context));
    varScope.addSVar("Transient_0_0", new InteropSDefT($Transient_0_0.instance, context));
    varScope.addSVar("Native_0_0", new InteropSDefT($Native_0_0.instance, context));
    varScope.addSVar("Static_0_0", new InteropSDefT($Static_0_0.instance, context));
    varScope.addSVar("Final_0_0", new InteropSDefT($Final_0_0.instance, context));
    varScope.addSVar("Abstract_0_0", new InteropSDefT($Abstract_0_0.instance, context));
    varScope.addSVar("Protected_0_0", new InteropSDefT($Protected_0_0.instance, context));
    varScope.addSVar("Private_0_0", new InteropSDefT($Private_0_0.instance, context));
    varScope.addSVar("Public_0_0", new InteropSDefT($Public_0_0.instance, context));
    varScope.addSVar("Id_1_0", new InteropSDefT($Id_1_0.instance, context));
    varScope.addSVar("NamedEscape_1_0", new InteropSDefT($Named$Escape_1_0.instance, context));
    varScope.addSVar("RuleNames_1_0", new InteropSDefT($Rule$Names_1_0.instance, context));
    varScope.addSVar("RDecT_3_0", new InteropSDefT($R$Dec$T_3_0.instance, context));
    varScope.addSVar("RDec_2_0", new InteropSDefT($R$Dec_2_0.instance, context));
    varScope.addSVar("RDecNoArgs_1_0", new InteropSDefT($R$Dec$No$Args_1_0.instance, context));
    varScope.addSVar("DynRuleScopeId_1_0", new InteropSDefT($Dyn$Rule$Scope$Id_1_0.instance, context));
    varScope.addSVar("LabeledDynRuleScopeId_2_0", new InteropSDefT($Labeled$Dyn$Rule$Scope$Id_2_0.instance, context));
    varScope.addSVar("DynRuleId_1_0", new InteropSDefT($Dyn$Rule$Id_1_0.instance, context));
    varScope.addSVar("AddLabelDynRuleId_2_0", new InteropSDefT($Add$Label$Dyn$Rule$Id_2_0.instance, context));
    varScope.addSVar("LabeledDynRuleId_2_0", new InteropSDefT($Labeled$Dyn$Rule$Id_2_0.instance, context));
    varScope.addSVar("SetDynRuleDepends_3_0", new InteropSDefT($Set$Dyn$Rule$Depends_3_0.instance, context));
    varScope.addSVar("DynRuleAssignAdd_2_0", new InteropSDefT($Dyn$Rule$Assign$Add_2_0.instance, context));
    varScope.addSVar("DynRuleAssign_2_0", new InteropSDefT($Dyn$Rule$Assign_2_0.instance, context));
    varScope.addSVar("SetDynRuleMatch_2_0", new InteropSDefT($Set$Dyn$Rule$Match_2_0.instance, context));
    varScope.addSVar("AddDynRule_2_0", new InteropSDefT($Add$Dyn$Rule_2_0.instance, context));
    varScope.addSVar("SetDynRule_2_0", new InteropSDefT($Set$Dyn$Rule_2_0.instance, context));
    varScope.addSVar("UndefineDynRule_2_0", new InteropSDefT($Undefine$Dyn$Rule_2_0.instance, context));
    varScope.addSVar("AddScopeLabel_2_0", new InteropSDefT($Add$Scope$Label_2_0.instance, context));
    varScope.addSVar("ScopeLabels_1_0", new InteropSDefT($Scope$Labels_1_0.instance, context));
    varScope.addSVar("WithClause_1_0", new InteropSDefT($With$Clause_1_0.instance, context));
    varScope.addSVar("WhereClause_1_0", new InteropSDefT($Where$Clause_1_0.instance, context));
    varScope.addSVar("Rule_3_0", new InteropSDefT($Rule_3_0.instance, context));
    varScope.addSVar("RuleNoCond_2_0", new InteropSDefT($Rule$No$Cond_2_0.instance, context));
    varScope.addSVar("RDefT_4_0", new InteropSDefT($R$Def$T_4_0.instance, context));
    varScope.addSVar("RDef_3_0", new InteropSDefT($R$Def_3_0.instance, context));
    varScope.addSVar("RDefNoArgs_2_0", new InteropSDefT($R$Def$No$Args_2_0.instance, context));
    varScope.addSVar("Overlay_3_0", new InteropSDefT($Overlay_3_0.instance, context));
    varScope.addSVar("OverlayNoArgs_2_0", new InteropSDefT($Overlay$No$Args_2_0.instance, context));
    varScope.addSVar("SwitchCase_2_0", new InteropSDefT($Switch$Case_2_0.instance, context));
    varScope.addSVar("StrategyCurly_1_0", new InteropSDefT($Strategy$Curly_1_0.instance, context));
    varScope.addSVar("ListVar_1_0", new InteropSDefT($List$Var_1_0.instance, context));
    varScope.addSVar("ImportWildcard_1_0", new InteropSDefT($Import$Wildcard_1_0.instance, context));
    varScope.addSVar("Import_1_0", new InteropSDefT($Import_1_0.instance, context));
    varScope.addSVar("Overlays_1_0", new InteropSDefT($Overlays_1_0.instance, context));
    varScope.addSVar("Rules_1_0", new InteropSDefT($Rules_1_0.instance, context));
    varScope.addSVar("Signature_1_0", new InteropSDefT($Signature_1_0.instance, context));
    varScope.addSVar("Strategies_1_0", new InteropSDefT($Strategies_1_0.instance, context));
    varScope.addSVar("Imports_1_0", new InteropSDefT($Imports_1_0.instance, context));
    varScope.addSVar("Specification_1_0", new InteropSDefT($Specification_1_0.instance, context));
    varScope.addSVar("Module_2_0", new InteropSDefT($Module_2_0.instance, context));
    varScope.addSVar("ParenStrat_1_0", new InteropSDefT($Paren$Strat_1_0.instance, context));
    varScope.addSVar("DefaultVarDec_1_0", new InteropSDefT($Default$Var$Dec_1_0.instance, context));
    varScope.addSVar("SDef_3_0", new InteropSDefT($S$Def_3_0.instance, context));
    varScope.addSVar("SDefNoArgs_2_0", new InteropSDefT($S$Def$No$Args_2_0.instance, context));
    varScope.addSVar("ExtSDef_3_0", new InteropSDefT($Ext$S$Def_3_0.instance, context));
    varScope.addSVar("ExtSDefInl_4_0", new InteropSDefT($Ext$S$Def$Inl_4_0.instance, context));
    varScope.addSVar("SDefT_4_0", new InteropSDefT($S$Def$T_4_0.instance, context));
    varScope.addSVar("DynRuleIntersectUnion_4_0", new InteropSDefT($Dyn$Rule$Intersect$Union_4_0.instance, context));
    varScope.addSVar("DynRuleUnion_3_0", new InteropSDefT($Dyn$Rule$Union_3_0.instance, context));
    varScope.addSVar("DynRuleIntersect_3_0", new InteropSDefT($Dyn$Rule$Intersect_3_0.instance, context));
    varScope.addSVar("DynRuleIntersectUnionFix_3_0", new InteropSDefT($Dyn$Rule$Intersect$Union$Fix_3_0.instance, context));
    varScope.addSVar("DynRuleUnionFix_2_0", new InteropSDefT($Dyn$Rule$Union$Fix_2_0.instance, context));
    varScope.addSVar("DynRuleIntersectFix_2_0", new InteropSDefT($Dyn$Rule$Intersect$Fix_2_0.instance, context));
    varScope.addSVar("GenDynRules_1_0", new InteropSDefT($Gen$Dyn$Rules_1_0.instance, context));
    varScope.addSVar("DynRuleScope_2_0", new InteropSDefT($Dyn$Rule$Scope_2_0.instance, context));
    varScope.addSVar("AM_2_0", new InteropSDefT($A$M_2_0.instance, context));
    varScope.addSVar("SwitchChoice_3_0", new InteropSDefT($Switch$Choice_3_0.instance, context));
    varScope.addSVar("SwitchChoiceNoOtherwise_2_0", new InteropSDefT($Switch$Choice$No$Otherwise_2_0.instance, context));
    varScope.addSVar("IfThen_2_0", new InteropSDefT($If$Then_2_0.instance, context));
    varScope.addSVar("CondChoice_3_0", new InteropSDefT($Cond$Choice_3_0.instance, context));
    varScope.addSVar("RChoice_2_0", new InteropSDefT($R$Choice_2_0.instance, context));
    varScope.addSVar("Choice_2_0", new InteropSDefT($Choice_2_0.instance, context));
    varScope.addSVar("SRule_1_0", new InteropSDefT($S$Rule_1_0.instance, context));
    varScope.addSVar("LRule_1_0", new InteropSDefT($L$Rule_1_0.instance, context));
    varScope.addSVar("CallNoArgs_1_0", new InteropSDefT($Call$No$Args_1_0.instance, context));
    varScope.addSVar("ExplodeCong_2_0", new InteropSDefT($Explode$Cong_2_0.instance, context));
    varScope.addSVar("ListCong_2_0", new InteropSDefT($List$Cong_2_0.instance, context));
    varScope.addSVar("ListCongNoTail_1_0", new InteropSDefT($List$Cong$No$Tail_1_0.instance, context));
    varScope.addSVar("TupleCong_2_0", new InteropSDefT($Tuple$Cong_2_0.instance, context));
    varScope.addSVar("EmptyTupleCong_0_0", new InteropSDefT($Empty$Tuple$Cong_0_0.instance, context));
    varScope.addSVar("AnnoCong_2_0", new InteropSDefT($Anno$Cong_2_0.instance, context));
    varScope.addSVar("CongQ_2_0", new InteropSDefT($Cong$Q_2_0.instance, context));
    varScope.addSVar("CharCong_1_0", new InteropSDefT($Char$Cong_1_0.instance, context));
    varScope.addSVar("RealCong_1_0", new InteropSDefT($Real$Cong_1_0.instance, context));
    varScope.addSVar("IntCong_1_0", new InteropSDefT($Int$Cong_1_0.instance, context));
    varScope.addSVar("StrCong_1_0", new InteropSDefT($Str$Cong_1_0.instance, context));
    varScope.addSVar("Prim_2_0", new InteropSDefT($Prim_2_0.instance, context));
    varScope.addSVar("PrimNoArgs_1_0", new InteropSDefT($Prim$No$Args_1_0.instance, context));
    varScope.addSVar("Test_1_0", new InteropSDefT($Test_1_0.instance, context));
    varScope.addSVar("With_1_0", new InteropSDefT($With_1_0.instance, context));
    varScope.addSVar("Where_1_0", new InteropSDefT($Where_1_0.instance, context));
    varScope.addSVar("Rec_2_0", new InteropSDefT($Rec_2_0.instance, context));
    varScope.addSVar("LChoice_2_0", new InteropSDefT($L$Choice_2_0.instance, context));
    varScope.addSVar("BA_2_0", new InteropSDefT($B$A_2_0.instance, context));
    varScope.addSVar("ScopeDefault_1_0", new InteropSDefT($Scope$Default_1_0.instance, context));
    varScope.addSVar("Call_2_0", new InteropSDefT($Call_2_0.instance, context));
    varScope.addSVar("ImportTerm_1_0", new InteropSDefT($Import$Term_1_0.instance, context));
    varScope.addSVar("All_1_0", new InteropSDefT($All_1_0.instance, context));
    varScope.addSVar("One_1_0", new InteropSDefT($One_1_0.instance, context));
    varScope.addSVar("PrimT_3_0", new InteropSDefT($Prim$T_3_0.instance, context));
    varScope.addSVar("GuardedLChoice_3_0", new InteropSDefT($Guarded$L$Choice_3_0.instance, context));
    varScope.addSVar("Seq_2_0", new InteropSDefT($Seq_2_0.instance, context));
    varScope.addSVar("Scope_2_0", new InteropSDefT($Scope_2_0.instance, context));
    varScope.addSVar("Build_1_0", new InteropSDefT($Build_1_0.instance, context));
    varScope.addSVar("Match_1_0", new InteropSDefT($Match_1_0.instance, context));
    varScope.addSVar("Id_0_0", new InteropSDefT($Id_0_0.instance, context));
    varScope.addSVar("Fail_0_0", new InteropSDefT($Fail_0_0.instance, context));
    varScope.addSVar("CallDynamic_3_0", new InteropSDefT($Call$Dynamic_3_0.instance, context));
    varScope.addSVar("CallT_3_0", new InteropSDefT($Call$T_3_0.instance, context));
    varScope.addSVar("Let_2_0", new InteropSDefT($Let_2_0.instance, context));
    varScope.addSVar("SVar_1_0", new InteropSDefT($S$Var_1_0.instance, context));
    varScope.addSVar("FunType_2_0", new InteropSDefT($Fun$Type_2_0.instance, context));
    varScope.addSVar("ConstType_1_0", new InteropSDefT($Const$Type_1_0.instance, context));
    varScope.addSVar("ExtOpDeclInj_1_0", new InteropSDefT($Ext$Op$Decl$Inj_1_0.instance, context));
    varScope.addSVar("ExtOpDeclQ_2_0", new InteropSDefT($Ext$Op$Decl$Q_2_0.instance, context));
    varScope.addSVar("ExtOpDecl_2_0", new InteropSDefT($Ext$Op$Decl_2_0.instance, context));
    varScope.addSVar("OpDeclInj_1_0", new InteropSDefT($Op$Decl$Inj_1_0.instance, context));
    varScope.addSVar("OpDeclQ_2_0", new InteropSDefT($Op$Decl$Q_2_0.instance, context));
    varScope.addSVar("OpDecl_2_0", new InteropSDefT($Op$Decl_2_0.instance, context));
    varScope.addSVar("SortTuple_1_0", new InteropSDefT($Sort$Tuple_1_0.instance, context));
    varScope.addSVar("SortListTl_2_0", new InteropSDefT($Sort$List$Tl_2_0.instance, context));
    varScope.addSVar("SortList_1_0", new InteropSDefT($Sort$List_1_0.instance, context));
    varScope.addSVar("Sort_2_0", new InteropSDefT($Sort_2_0.instance, context));
    varScope.addSVar("SortNoArgs_1_0", new InteropSDefT($Sort$No$Args_1_0.instance, context));
    varScope.addSVar("SortVar_1_0", new InteropSDefT($Sort$Var_1_0.instance, context));
    varScope.addSVar("Constructors_1_0", new InteropSDefT($Constructors_1_0.instance, context));
    varScope.addSVar("Sorts_1_0", new InteropSDefT($Sorts_1_0.instance, context));
    varScope.addSVar("Wld_0_0", new InteropSDefT($Wld_0_0.instance, context));
    varScope.addSVar("RootApp_1_0", new InteropSDefT($Root$App_1_0.instance, context));
    varScope.addSVar("App_2_0", new InteropSDefT($App_2_0.instance, context));
    varScope.addSVar("NoAnnoList_1_0", new InteropSDefT($No$Anno$List_1_0.instance, context));
    varScope.addSVar("AnnoList_2_0", new InteropSDefT($Anno$List_2_0.instance, context));
    varScope.addSVar("BuildDefault_1_0", new InteropSDefT($Build$Default_1_0.instance, context));
    varScope.addSVar("As_2_0", new InteropSDefT($As_2_0.instance, context));
    varScope.addSVar("ListTail_2_0", new InteropSDefT($List$Tail_2_0.instance, context));
    varScope.addSVar("List_1_0", new InteropSDefT($List_1_0.instance, context));
    varScope.addSVar("Tuple_1_0", new InteropSDefT($Tuple_1_0.instance, context));
    varScope.addSVar("BuildDefaultPT_1_0", new InteropSDefT($Build$Default$P$T_1_0.instance, context));
    varScope.addSVar("Explode_2_0", new InteropSDefT($Explode_2_0.instance, context));
    varScope.addSVar("OpQ_2_0", new InteropSDefT($Op$Q_2_0.instance, context));
    varScope.addSVar("Op_2_0", new InteropSDefT($Op_2_0.instance, context));
    varScope.addSVar("Str_1_0", new InteropSDefT($Str_1_0.instance, context));
    varScope.addSVar("Real_1_0", new InteropSDefT($Real_1_0.instance, context));
    varScope.addSVar("Int_1_0", new InteropSDefT($Int_1_0.instance, context));
    varScope.addSVar("Var_1_0", new InteropSDefT($Var_1_0.instance, context));
  }

  private void registerLazy(org.spoofax.interpreter.core.IContext context, Context compiledContext, ClassLoader classLoader, org.spoofax.interpreter.core.VarScope varScope)
  { 
    compiledContext.registerComponent("renaming");
    renaming.init(compiledContext);
    varScope.addSVar("rename_rules_0_2", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.rename_rules_0_2", context));
    varScope.addSVar("rename_rule_0_2", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.rename_rule_0_2", context));
    varScope.addSVar("apply_renaming_0_3", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.apply_renaming_0_3", context));
    varScope.addSVar("rename_java_0_3", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.rename_java_0_3", context));
    varScope.addSVar("rename_sugardec_0_2", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.rename_sugardec_0_2", context));
    varScope.addSVar("rename_modeldec_0_2", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.rename_modeldec_0_2", context));
    varScope.addSVar("rename_editordec_0_2", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.rename_editordec_0_2", context));
    varScope.addSVar("do_rename_java_0_3", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.do_rename_java_0_3", context));
    varScope.addSVar("match_pkgs_java_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.match_pkgs_java_0_0", context));
    varScope.addSVar("ToModelTerm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$To$Model$Term_1_0", context));
    varScope.addSVar("TransApp_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Trans$App_2_0", context));
    varScope.addSVar("transformation_elem_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.transformation_elem_1_0", context));
    varScope.addSVar("grammar_elem_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.grammar_elem_1_0", context));
    varScope.addSVar("Desugarings_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Desugarings_1_0", context));
    varScope.addSVar("InjectDesugaring_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Inject$Desugaring_4_0", context));
    varScope.addSVar("PureDesugaring_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Pure$Desugaring_1_0", context));
    varScope.addSVar("CompilationUnit_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Compilation$Unit_3_0", context));
    varScope.addSVar("CompileError_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Compile$Error_2_0", context));
    varScope.addSVar("SugarBody_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sugar$Body_1_0", context));
    varScope.addSVar("SugarDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sugar$Dec_2_0", context));
    varScope.addSVar("SugarDecHead_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sugar$Dec$Head_2_0", context));
    varScope.addSVar("EditorServicesDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Editor$Services$Dec_2_0", context));
    varScope.addSVar("EditorServicesDecHead_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Editor$Services$Dec$Head_2_0", context));
    varScope.addSVar("EditorServicesBody_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Editor$Services$Body_1_0", context));
    varScope.addSVar("ChecksDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Checks$Dec_2_0", context));
    varScope.addSVar("ChecksDecHead_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Checks$Dec$Head_2_0", context));
    varScope.addSVar("ChecksBody_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Checks$Body_1_0", context));
    varScope.addSVar("ModelDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Model$Dec_2_0", context));
    varScope.addSVar("ModelDecHead_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Model$Dec$Head_3_0", context));
    varScope.addSVar("ModelBody_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Model$Body_1_0", context));
    varScope.addSVar("TransDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Trans$Dec_2_0", context));
    varScope.addSVar("TransDecHead_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Trans$Dec$Head_2_0", context));
    varScope.addSVar("TransBody_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Trans$Body_1_0", context));
    varScope.addSVar("TransImportDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Trans$Import$Dec_2_0", context));
    varScope.addSVar("TypeImportAsDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Import$As$Dec_2_0", context));
    varScope.addSVar("ImportAs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Import$As_1_0", context));
    varScope.addSVar("Semicolon_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Semicolon_0_0", context));
    varScope.addSVar("StaticImportOnDemandDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Static$Import$On$Demand$Dec_1_0", context));
    varScope.addSVar("StaticImportDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Static$Import$Dec_2_0", context));
    varScope.addSVar("TypeImportOnDemandDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Import$On$Demand$Dec_1_0", context));
    varScope.addSVar("TypeImportDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Import$Dec_1_0", context));
    varScope.addSVar("PackageDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Package$Dec_2_0", context));
    varScope.addSVar("ElemValArrayInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Elem$Val$Array$Init_1_0", context));
    varScope.addSVar("ElemValPair_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Elem$Val$Pair_2_0", context));
    varScope.addSVar("MarkerAnno_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Marker$Anno_1_0", context));
    varScope.addSVar("SingleElemAnno_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Single$Elem$Anno_2_0", context));
    varScope.addSVar("GenericMethod_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Generic$Method_3_0", context));
    varScope.addSVar("QSuperMethod_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Q$Super$Method_3_0", context));
    varScope.addSVar("SuperMethod_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Super$Method_2_0", context));
    varScope.addSVar("Method_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Method_3_0", context));
    varScope.addSVar("Method_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Method_1_0", context));
    varScope.addSVar("QSuperField_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Q$Super$Field_2_0", context));
    varScope.addSVar("SuperField_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Super$Field_1_0", context));
    varScope.addSVar("Field_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Field_2_0", context));
    varScope.addSVar("Dim_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dim_1_0", context));
    varScope.addSVar("UnboundWld_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Unbound$Wld_1_0", context));
    varScope.addSVar("NewArray_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$New$Array_3_0", context));
    varScope.addSVar("ImplementsDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Implements$Dec_1_0", context));
    varScope.addSVar("SuperDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Super$Dec_1_0", context));
    varScope.addSVar("ClassDecHead_5_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Class$Dec$Head_5_0", context));
    varScope.addSVar("ClassBody_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Class$Body_1_0", context));
    varScope.addSVar("ClassDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Class$Dec_2_0", context));
    varScope.addSVar("ExtendsInterfaces_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Extends$Interfaces_1_0", context));
    varScope.addSVar("InterfaceDecHead_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Interface$Dec$Head_4_0", context));
    varScope.addSVar("InterfaceDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Interface$Dec_2_0", context));
    varScope.addSVar("DefaultVal_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Default$Val_1_0", context));
    varScope.addSVar("AnnoMethodDec_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Anno$Method$Dec_4_0", context));
    varScope.addSVar("AnnoDecHead_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Anno$Dec$Head_2_0", context));
    varScope.addSVar("AnnoDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Anno$Dec_2_0", context));
    varScope.addSVar("DeprAbstractMethodDec_7_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Depr$Abstract$Method$Dec_7_0", context));
    varScope.addSVar("AbstractMethodDec_6_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Abstract$Method$Dec_6_0", context));
    varScope.addSVar("ConstantDec_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Constant$Dec_3_0", context));
    varScope.addSVar("EnumBodyDecs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Enum$Body$Decs_1_0", context));
    varScope.addSVar("EnumConst_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Enum$Const_3_0", context));
    varScope.addSVar("EnumBody_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Enum$Body_2_0", context));
    varScope.addSVar("EnumDecHead_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Enum$Dec$Head_3_0", context));
    varScope.addSVar("EnumDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Enum$Dec_2_0", context));
    varScope.addSVar("QSuperConstrInv_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Q$Super$Constr$Inv_3_0", context));
    varScope.addSVar("SuperConstrInv_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Super$Constr$Inv_2_0", context));
    varScope.addSVar("AltConstrInv_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Alt$Constr$Inv_2_0", context));
    varScope.addSVar("ConstrBody_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Constr$Body_2_0", context));
    varScope.addSVar("ConstrDecHead_5_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Constr$Dec$Head_5_0", context));
    varScope.addSVar("ConstrDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Constr$Dec_2_0", context));
    varScope.addSVar("StaticInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Static$Init_1_0", context));
    varScope.addSVar("InstanceInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Instance$Init_1_0", context));
    varScope.addSVar("NoMethodBody_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$No$Method$Body_0_0", context));
    varScope.addSVar("ThrowsDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Throws$Dec_1_0", context));
    varScope.addSVar("VarArityParam_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Var$Arity$Param_3_0", context));
    varScope.addSVar("Param_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Param_3_0", context));
    varScope.addSVar("Void_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Void_0_0", context));
    varScope.addSVar("DeprMethodDecHead_7_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Depr$Method$Dec$Head_7_0", context));
    varScope.addSVar("MethodDecHead_6_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Method$Dec$Head_6_0", context));
    varScope.addSVar("MethodDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Method$Dec_2_0", context));
    varScope.addSVar("ClassDecStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Class$Dec$Stm_1_0", context));
    varScope.addSVar("Block_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Block_1_0", context));
    varScope.addSVar("Default_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Default_0_0", context));
    varScope.addSVar("Case_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Case_1_0", context));
    varScope.addSVar("SwitchGroup_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Switch$Group_2_0", context));
    varScope.addSVar("SwitchBlock_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Switch$Block_2_0", context));
    varScope.addSVar("Try_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Try_3_0", context));
    varScope.addSVar("Try_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Try_2_0", context));
    varScope.addSVar("Synchronized_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Synchronized_2_0", context));
    varScope.addSVar("Throw_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Throw_1_0", context));
    varScope.addSVar("Return_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Return_1_0", context));
    varScope.addSVar("Continue_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Continue_1_0", context));
    varScope.addSVar("Break_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Break_1_0", context));
    varScope.addSVar("ForEach_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$For$Each_3_0", context));
    varScope.addSVar("For_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$For_4_0", context));
    varScope.addSVar("DoWhile_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Do$While_2_0", context));
    varScope.addSVar("While_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$While_2_0", context));
    varScope.addSVar("Switch_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Switch_2_0", context));
    varScope.addSVar("AssertStm_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assert$Stm_2_0", context));
    varScope.addSVar("AssertStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assert$Stm_1_0", context));
    varScope.addSVar("If_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$If_3_0", context));
    varScope.addSVar("If_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$If_2_0", context));
    varScope.addSVar("ExprStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Expr$Stm_1_0", context));
    varScope.addSVar("Labeled_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Labeled_2_0", context));
    varScope.addSVar("Empty_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Empty_0_0", context));
    varScope.addSVar("LocalVarDec_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Local$Var$Dec_3_0", context));
    varScope.addSVar("LocalVarDecStm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Local$Var$Dec$Stm_1_0", context));
    varScope.addSVar("Dim_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dim_0_0", context));
    varScope.addSVar("ArrayVarDecId_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Array$Var$Dec$Id_2_0", context));
    varScope.addSVar("VarDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Var$Dec_2_0", context));
    varScope.addSVar("VarDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Var$Dec_1_0", context));
    varScope.addSVar("FieldDec_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Field$Dec_3_0", context));
    varScope.addSVar("ArrayInit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Array$Init_1_0", context));
    varScope.addSVar("VoidClass_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Void$Class_0_0", context));
    varScope.addSVar("Class_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Class_1_0", context));
    varScope.addSVar("AssignOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Or_2_0", context));
    varScope.addSVar("AssignExcOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Exc$Or_2_0", context));
    varScope.addSVar("AssignAnd_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$And_2_0", context));
    varScope.addSVar("AssignURightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$U$Right$Shift_2_0", context));
    varScope.addSVar("AssignRightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Right$Shift_2_0", context));
    varScope.addSVar("AssignLeftShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Left$Shift_2_0", context));
    varScope.addSVar("AssignMinus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Minus_2_0", context));
    varScope.addSVar("AssignPlus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Plus_2_0", context));
    varScope.addSVar("AssignRemain_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Remain_2_0", context));
    varScope.addSVar("AssignDiv_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Div_2_0", context));
    varScope.addSVar("AssignMul_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign$Mul_2_0", context));
    varScope.addSVar("Assign_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Assign_2_0", context));
    varScope.addSVar("Or_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Or_2_0", context));
    varScope.addSVar("ExcOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Exc$Or_2_0", context));
    varScope.addSVar("And_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$And_2_0", context));
    varScope.addSVar("LazyOr_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Lazy$Or_2_0", context));
    varScope.addSVar("LazyAnd_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Lazy$And_2_0", context));
    varScope.addSVar("NotEq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Not$Eq_2_0", context));
    varScope.addSVar("Eq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Eq_2_0", context));
    varScope.addSVar("GtEq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Gt$Eq_2_0", context));
    varScope.addSVar("LtEq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Lt$Eq_2_0", context));
    varScope.addSVar("Gt_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Gt_2_0", context));
    varScope.addSVar("Lt_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Lt_2_0", context));
    varScope.addSVar("URightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$U$Right$Shift_2_0", context));
    varScope.addSVar("RightShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Right$Shift_2_0", context));
    varScope.addSVar("LeftShift_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Left$Shift_2_0", context));
    varScope.addSVar("Minus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Minus_2_0", context));
    varScope.addSVar("Plus_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Plus_2_0", context));
    varScope.addSVar("Remain_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Remain_2_0", context));
    varScope.addSVar("Div_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Div_2_0", context));
    varScope.addSVar("Mul_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Mul_2_0", context));
    varScope.addSVar("InstanceOf_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Instance$Of_2_0", context));
    varScope.addSVar("CastRef_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Cast$Ref_2_0", context));
    varScope.addSVar("CastPrim_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Cast$Prim_2_0", context));
    varScope.addSVar("Not_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Not_1_0", context));
    varScope.addSVar("Complement_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Complement_1_0", context));
    varScope.addSVar("PreDecr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Pre$Decr_1_0", context));
    varScope.addSVar("PreIncr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Pre$Incr_1_0", context));
    varScope.addSVar("Minus_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Minus_1_0", context));
    varScope.addSVar("Plus_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Plus_1_0", context));
    varScope.addSVar("PostDecr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Post$Decr_1_0", context));
    varScope.addSVar("PostIncr_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Post$Incr_1_0", context));
    varScope.addSVar("Invoke_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Invoke_2_0", context));
    varScope.addSVar("QNewInstance_6_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Q$New$Instance_6_0", context));
    varScope.addSVar("NewInstance_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$New$Instance_4_0", context));
    varScope.addSVar("QThis_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Q$This_1_0", context));
    varScope.addSVar("This_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$This_0_0", context));
    varScope.addSVar("Lit_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Lit_1_0", context));
    varScope.addSVar("ArrayType_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Array$Type_1_0", context));
    varScope.addSVar("TypeVar_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Var_1_0", context));
    varScope.addSVar("Member_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Member_3_0", context));
    varScope.addSVar("InterfaceType_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Interface$Type_2_0", context));
    varScope.addSVar("ClassType_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Class$Type_2_0", context));
    varScope.addSVar("ClassOrInterfaceType_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Class$Or$Interface$Type_2_0", context));
    varScope.addSVar("TypeParams_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Params_1_0", context));
    varScope.addSVar("TypeBound_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Bound_1_0", context));
    varScope.addSVar("TypeParam_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Param_2_0", context));
    varScope.addSVar("WildcardLowerBound_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Wildcard$Lower$Bound_1_0", context));
    varScope.addSVar("WildcardUpperBound_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Wildcard$Upper$Bound_1_0", context));
    varScope.addSVar("Wildcard_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Wildcard_1_0", context));
    varScope.addSVar("TypeArgs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Args_1_0", context));
    varScope.addSVar("PackageOrTypeName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Package$Or$Type$Name_2_0", context));
    varScope.addSVar("PackageOrTypeName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Package$Or$Type$Name_1_0", context));
    varScope.addSVar("MethodName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Method$Name_2_0", context));
    varScope.addSVar("MethodName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Method$Name_1_0", context));
    varScope.addSVar("ExprName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Expr$Name_2_0", context));
    varScope.addSVar("ExprName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Expr$Name_1_0", context));
    varScope.addSVar("TypeName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Name_2_0", context));
    varScope.addSVar("TypeName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Type$Name_1_0", context));
    varScope.addSVar("AmbName_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Amb$Name_2_0", context));
    varScope.addSVar("AmbName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Amb$Name_1_0", context));
    varScope.addSVar("PackageName_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Package$Name_1_0", context));
    varScope.addSVar("Double_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Double_0_0", context));
    varScope.addSVar("Float_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Float_0_0", context));
    varScope.addSVar("Char_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Char_0_0", context));
    varScope.addSVar("Long_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Long_0_0", context));
    varScope.addSVar("Int_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Int_0_0", context));
    varScope.addSVar("Short_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Short_0_0", context));
    varScope.addSVar("Byte_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Byte_0_0", context));
    varScope.addSVar("Boolean_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Boolean_0_0", context));
    varScope.addSVar("Null_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Null_0_0", context));
    varScope.addSVar("Chars_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Chars_1_0", context));
    varScope.addSVar("String_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$String_1_0", context));
    varScope.addSVar("Single_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Single_1_0", context));
    varScope.addSVar("Char_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Char_1_0", context));
    varScope.addSVar("False_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$False_0_0", context));
    varScope.addSVar("True_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$True_0_0", context));
    varScope.addSVar("Bool_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Bool_1_0", context));
    varScope.addSVar("Float_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Float_1_0", context));
    varScope.addSVar("Octa_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Octa_1_0", context));
    varScope.addSVar("Hexa_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Hexa_1_0", context));
    varScope.addSVar("Deci_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Deci_1_0", context));
    varScope.addSVar("StrictFP_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Strict$F$P_0_0", context));
    varScope.addSVar("Synchronized_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Synchronized_0_0", context));
    varScope.addSVar("Volatile_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Volatile_0_0", context));
    varScope.addSVar("Transient_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Transient_0_0", context));
    varScope.addSVar("Native_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Native_0_0", context));
    varScope.addSVar("Static_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Static_0_0", context));
    varScope.addSVar("Final_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Final_0_0", context));
    varScope.addSVar("Abstract_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Abstract_0_0", context));
    varScope.addSVar("Protected_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Protected_0_0", context));
    varScope.addSVar("Private_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Private_0_0", context));
    varScope.addSVar("Public_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Public_0_0", context));
    varScope.addSVar("Id_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Id_1_0", context));
    varScope.addSVar("NamedEscape_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Named$Escape_1_0", context));
    varScope.addSVar("RuleNames_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Rule$Names_1_0", context));
    varScope.addSVar("RDecT_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$R$Dec$T_3_0", context));
    varScope.addSVar("RDec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$R$Dec_2_0", context));
    varScope.addSVar("RDecNoArgs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$R$Dec$No$Args_1_0", context));
    varScope.addSVar("DynRuleScopeId_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Scope$Id_1_0", context));
    varScope.addSVar("LabeledDynRuleScopeId_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Labeled$Dyn$Rule$Scope$Id_2_0", context));
    varScope.addSVar("DynRuleId_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Id_1_0", context));
    varScope.addSVar("AddLabelDynRuleId_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Add$Label$Dyn$Rule$Id_2_0", context));
    varScope.addSVar("LabeledDynRuleId_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Labeled$Dyn$Rule$Id_2_0", context));
    varScope.addSVar("SetDynRuleDepends_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Set$Dyn$Rule$Depends_3_0", context));
    varScope.addSVar("DynRuleAssignAdd_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Assign$Add_2_0", context));
    varScope.addSVar("DynRuleAssign_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Assign_2_0", context));
    varScope.addSVar("SetDynRuleMatch_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Set$Dyn$Rule$Match_2_0", context));
    varScope.addSVar("AddDynRule_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Add$Dyn$Rule_2_0", context));
    varScope.addSVar("SetDynRule_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Set$Dyn$Rule_2_0", context));
    varScope.addSVar("UndefineDynRule_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Undefine$Dyn$Rule_2_0", context));
    varScope.addSVar("AddScopeLabel_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Add$Scope$Label_2_0", context));
    varScope.addSVar("ScopeLabels_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Scope$Labels_1_0", context));
    varScope.addSVar("WithClause_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$With$Clause_1_0", context));
    varScope.addSVar("WhereClause_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Where$Clause_1_0", context));
    varScope.addSVar("Rule_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Rule_3_0", context));
    varScope.addSVar("RuleNoCond_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Rule$No$Cond_2_0", context));
    varScope.addSVar("RDefT_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$R$Def$T_4_0", context));
    varScope.addSVar("RDef_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$R$Def_3_0", context));
    varScope.addSVar("RDefNoArgs_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$R$Def$No$Args_2_0", context));
    varScope.addSVar("Overlay_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Overlay_3_0", context));
    varScope.addSVar("OverlayNoArgs_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Overlay$No$Args_2_0", context));
    varScope.addSVar("SwitchCase_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Switch$Case_2_0", context));
    varScope.addSVar("StrategyCurly_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Strategy$Curly_1_0", context));
    varScope.addSVar("ListVar_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$List$Var_1_0", context));
    varScope.addSVar("ImportWildcard_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Import$Wildcard_1_0", context));
    varScope.addSVar("Import_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Import_1_0", context));
    varScope.addSVar("Overlays_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Overlays_1_0", context));
    varScope.addSVar("Rules_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Rules_1_0", context));
    varScope.addSVar("Signature_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Signature_1_0", context));
    varScope.addSVar("Strategies_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Strategies_1_0", context));
    varScope.addSVar("Imports_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Imports_1_0", context));
    varScope.addSVar("Specification_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Specification_1_0", context));
    varScope.addSVar("Module_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Module_2_0", context));
    varScope.addSVar("ParenStrat_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Paren$Strat_1_0", context));
    varScope.addSVar("DefaultVarDec_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Default$Var$Dec_1_0", context));
    varScope.addSVar("SDef_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$S$Def_3_0", context));
    varScope.addSVar("SDefNoArgs_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$S$Def$No$Args_2_0", context));
    varScope.addSVar("ExtSDef_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Ext$S$Def_3_0", context));
    varScope.addSVar("ExtSDefInl_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Ext$S$Def$Inl_4_0", context));
    varScope.addSVar("SDefT_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$S$Def$T_4_0", context));
    varScope.addSVar("DynRuleIntersectUnion_4_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Intersect$Union_4_0", context));
    varScope.addSVar("DynRuleUnion_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Union_3_0", context));
    varScope.addSVar("DynRuleIntersect_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Intersect_3_0", context));
    varScope.addSVar("DynRuleIntersectUnionFix_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Intersect$Union$Fix_3_0", context));
    varScope.addSVar("DynRuleUnionFix_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Union$Fix_2_0", context));
    varScope.addSVar("DynRuleIntersectFix_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Intersect$Fix_2_0", context));
    varScope.addSVar("GenDynRules_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Gen$Dyn$Rules_1_0", context));
    varScope.addSVar("DynRuleScope_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Dyn$Rule$Scope_2_0", context));
    varScope.addSVar("AM_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$A$M_2_0", context));
    varScope.addSVar("SwitchChoice_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Switch$Choice_3_0", context));
    varScope.addSVar("SwitchChoiceNoOtherwise_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Switch$Choice$No$Otherwise_2_0", context));
    varScope.addSVar("IfThen_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$If$Then_2_0", context));
    varScope.addSVar("CondChoice_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Cond$Choice_3_0", context));
    varScope.addSVar("RChoice_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$R$Choice_2_0", context));
    varScope.addSVar("Choice_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Choice_2_0", context));
    varScope.addSVar("SRule_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$S$Rule_1_0", context));
    varScope.addSVar("LRule_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$L$Rule_1_0", context));
    varScope.addSVar("CallNoArgs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Call$No$Args_1_0", context));
    varScope.addSVar("ExplodeCong_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Explode$Cong_2_0", context));
    varScope.addSVar("ListCong_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$List$Cong_2_0", context));
    varScope.addSVar("ListCongNoTail_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$List$Cong$No$Tail_1_0", context));
    varScope.addSVar("TupleCong_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Tuple$Cong_2_0", context));
    varScope.addSVar("EmptyTupleCong_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Empty$Tuple$Cong_0_0", context));
    varScope.addSVar("AnnoCong_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Anno$Cong_2_0", context));
    varScope.addSVar("CongQ_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Cong$Q_2_0", context));
    varScope.addSVar("CharCong_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Char$Cong_1_0", context));
    varScope.addSVar("RealCong_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Real$Cong_1_0", context));
    varScope.addSVar("IntCong_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Int$Cong_1_0", context));
    varScope.addSVar("StrCong_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Str$Cong_1_0", context));
    varScope.addSVar("Prim_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Prim_2_0", context));
    varScope.addSVar("PrimNoArgs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Prim$No$Args_1_0", context));
    varScope.addSVar("Test_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Test_1_0", context));
    varScope.addSVar("With_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$With_1_0", context));
    varScope.addSVar("Where_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Where_1_0", context));
    varScope.addSVar("Rec_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Rec_2_0", context));
    varScope.addSVar("LChoice_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$L$Choice_2_0", context));
    varScope.addSVar("BA_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$B$A_2_0", context));
    varScope.addSVar("ScopeDefault_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Scope$Default_1_0", context));
    varScope.addSVar("Call_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Call_2_0", context));
    varScope.addSVar("ImportTerm_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Import$Term_1_0", context));
    varScope.addSVar("All_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$All_1_0", context));
    varScope.addSVar("One_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$One_1_0", context));
    varScope.addSVar("PrimT_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Prim$T_3_0", context));
    varScope.addSVar("GuardedLChoice_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Guarded$L$Choice_3_0", context));
    varScope.addSVar("Seq_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Seq_2_0", context));
    varScope.addSVar("Scope_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Scope_2_0", context));
    varScope.addSVar("Build_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Build_1_0", context));
    varScope.addSVar("Match_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Match_1_0", context));
    varScope.addSVar("Id_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Id_0_0", context));
    varScope.addSVar("Fail_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Fail_0_0", context));
    varScope.addSVar("CallDynamic_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Call$Dynamic_3_0", context));
    varScope.addSVar("CallT_3_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Call$T_3_0", context));
    varScope.addSVar("Let_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Let_2_0", context));
    varScope.addSVar("SVar_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$S$Var_1_0", context));
    varScope.addSVar("FunType_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Fun$Type_2_0", context));
    varScope.addSVar("ConstType_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Const$Type_1_0", context));
    varScope.addSVar("ExtOpDeclInj_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Ext$Op$Decl$Inj_1_0", context));
    varScope.addSVar("ExtOpDeclQ_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Ext$Op$Decl$Q_2_0", context));
    varScope.addSVar("ExtOpDecl_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Ext$Op$Decl_2_0", context));
    varScope.addSVar("OpDeclInj_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Op$Decl$Inj_1_0", context));
    varScope.addSVar("OpDeclQ_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Op$Decl$Q_2_0", context));
    varScope.addSVar("OpDecl_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Op$Decl_2_0", context));
    varScope.addSVar("SortTuple_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sort$Tuple_1_0", context));
    varScope.addSVar("SortListTl_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sort$List$Tl_2_0", context));
    varScope.addSVar("SortList_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sort$List_1_0", context));
    varScope.addSVar("Sort_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sort_2_0", context));
    varScope.addSVar("SortNoArgs_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sort$No$Args_1_0", context));
    varScope.addSVar("SortVar_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sort$Var_1_0", context));
    varScope.addSVar("Constructors_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Constructors_1_0", context));
    varScope.addSVar("Sorts_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Sorts_1_0", context));
    varScope.addSVar("Wld_0_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Wld_0_0", context));
    varScope.addSVar("RootApp_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Root$App_1_0", context));
    varScope.addSVar("App_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$App_2_0", context));
    varScope.addSVar("NoAnnoList_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$No$Anno$List_1_0", context));
    varScope.addSVar("AnnoList_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Anno$List_2_0", context));
    varScope.addSVar("BuildDefault_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Build$Default_1_0", context));
    varScope.addSVar("As_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$As_2_0", context));
    varScope.addSVar("ListTail_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$List$Tail_2_0", context));
    varScope.addSVar("List_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$List_1_0", context));
    varScope.addSVar("Tuple_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Tuple_1_0", context));
    varScope.addSVar("BuildDefaultPT_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Build$Default$P$T_1_0", context));
    varScope.addSVar("Explode_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Explode_2_0", context));
    varScope.addSVar("OpQ_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Op$Q_2_0", context));
    varScope.addSVar("Op_2_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Op_2_0", context));
    varScope.addSVar("Str_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Str_1_0", context));
    varScope.addSVar("Real_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Real_1_0", context));
    varScope.addSVar("Int_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Int_1_0", context));
    varScope.addSVar("Var_1_0", new InteropSDefT(classLoader, "org.sugarj.driver.transformations.renaming.$Var_1_0", context));
  }
}