#!/bin/bash
# cai 17.08.12
# script to print classpath

# find base directory of sugarj
# CELEBRATION: No longer dependent on eclipse's location
sugarj="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
script="$sugarj/deployment/cli-script"
common="$sugarj/common/bin"
compiler="$sugarj/compiler/bin"
stdlib="$sugarj/stdlib/bin"
layout="$sugarj/layout-parsing/jsglr-layout/bin"
cliroot="$sugarj/compiler"
clijars="$cliroot/commons-cli-1.2.jar:$cliroot/strategoxt.jar:$cliroot/make_permissive.jar"
langroot="$sugarj/language-libraries"
langlibs="$langroot/base/bin:$langroot/haskell/bin:$langroot/java/bin:$langroot/prolog/bin"

# essential paths
classpath="$compiler:$clijars:$common:$stdlib:$langlibs:$layout"

# what we try to combine
# somehow the nativebundle does not cooperate no matter what I do with it
# zip, jar, etc won't help the star locate SDFBundleCommand.class
sdfbundle="$script/native"
classpath="$classpath:$sdfbundle"
classpath="$classpath:$script/jars/*"

exec echo "$classpath"
