#!/bin/bash
# utility to copy jars from eclipase/plugin to cli-script/jars quickly
# works only on cai's computer, and only when pwd==cli-script
# usage example: u/p org.eclipse.core.jobs_3.5.200.v20120521-2346.jar
plugindir="$HOME/etc/eclipsej/plugins"
cp -vr "$plugindir/$*" jars/
